Repository uspgamedev/backdoor, pull requests merged in 2018-06, with the labels that each got.

#726 Code formatting
  game/view/spritefx/number_rise.lua
Labels: refactoring

#727 Fix range input bug
  game/debug/view/input/common.lua
Labels: bug

#731 Bugfix/monsterdeath hang
  game/common/random.lua
  game/domain/builders/route.lua
  game/domain/sector.lua
  game/infra/profile.lua
Labels: bug, feature

#732 New layout
  .gitignore
  game/assets/texture/fakeminimap.png
  game/assets/texture/panel-theme.png
  game/common/color.lua
  game/database/domains/collection/anything.json
  game/database/resources/texture/panel-theme.json
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/definitions/aptitude.lua
  game/domain/definitions/colors.lua
  game/domain/definitions/placements.lua
  game/domain/route.lua
  game/draw.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/tests/interface.lua
  game/view/actor.lua
  game/view/actor/attr.lua
  game/view/actor/header.lua
  game/view/actor/minimap.lua
  game/view/actor/panel.lua
  game/view/actor/widgets.lua
  game/view/consumelist.lua
  game/view/hand.lua
  game/view/helpers/exp.lua
  game/view/shaders/gaussian.lua
  game/view/shaders/init.lua
  game/view/startmenu.lua
Labels: UX, feature, interface, juice

#735 Tweak consume list view
  game/view/consumelist.lua
Labels: UX, juice

#748 Preview card effects
  game/database/domains/card/fireball.json
  game/domain/ability.lua
  game/domain/card.lua
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/destroy_body.lua
  game/domain/effects/draw_card.lua
  game/domain/effects/give_pack.lua
  game/domain/effects/heal.lua
  game/domain/effects/lose_life.lua
  game/domain/effects/make_body.lua
  game/domain/effects/move_to.lua
  game/domain/effects/place_widget.lua
  game/domain/effects/place_widget_on_area.lua
  game/domain/effects/print.lua
  game/domain/effects/reward_pp.lua
  game/domain/operators/count_nearby_bodies.lua
  game/domain/operators/dice_throw.lua
  game/domain/operators/get_actor_body.lua
  game/domain/operators/get_attribute.lua
  game/domain/operators/get_body_pos.lua
  game/domain/operators/integer_binop.lua
  game/domain/operators/self.lua
  game/view/helpers/card.lua
Labels: UX

#747 Add win32 deploy
  .gitignore
  Makefile
  game/database/init.lua
Labels: feature

#756 Fix DB writing
  game/database/init.lua
Labels: bug

#757 Poorly implemented diagonal input from keyboard
  game/gamestates/action_menu.lua
  game/gamestates/user_turn.lua
  game/infra/dir.lua
Labels: feature, gameplay, minor

#758 Removed redundant description and added some new ones
  game/database/domains/card/ani_1.json
  game/database/domains/card/arc_1.json
  game/database/domains/card/battery.json
  game/database/domains/card/blind.json
  game/database/domains/card/calming_down.json
  game/database/domains/card/cor_1.json
  game/database/domains/card/divination.json
  game/database/domains/card/dropkick.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/flash.json
  game/database/domains/card/goggles.json
  game/database/domains/card/haste.json
  game/database/domains/card/healing_potion.json
  game/database/domains/card/illusion_of_darkness.json
  game/database/domains/card/jetboots.json
  game/database/domains/card/jump.json
  game/database/domains/card/laser-spear.json
  game/database/domains/card/meteor_blast.json
  game/database/domains/card/rage.json
  game/database/domains/card/reassemble.json
  game/database/domains/card/reinforce.json
  game/database/domains/card/reinforced-surface.json
  game/database/domains/card/rush.json
  game/database/domains/card/rusty-blaster.json
  game/database/domains/card/seedling-sap.json
  game/database/domains/card/sensor-bomb.json
  game/database/domains/card/spark_rod.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/stunned.json
  game/database/domains/card/tipsy.json
  game/database/domains/card/turret.json
  game/database/domains/card/wrench.json
Labels: feature, interface

#764 Uniformize domain builders
  game/database/schema/actor.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/builders/actor.lua
  game/domain/builders/body.lua
  game/domain/builders/buffers.lua
  game/domain/builders/card.lua
  game/domain/builders/sectors.lua
  game/domain/card.lua
  game/domain/effects/make_body.lua
  game/domain/route.lua
  game/domain/sector.lua
Labels: bug, refactoring

#768 Ability belt
  game/database/domains/actor/arcanist.json
  game/database/domains/actor/brawler.json
  game/database/domains/actor/gadgeteer.json
  game/database/domains/card/bolting.json
  game/database/domains/card/bullet.json
  game/database/domains/card/punch.json
  game/domain/definitions/colors.lua
  game/gamestates/ready_ability.lua
  game/gamestates/user_turn.lua
  game/main.lua
  game/view/readyability.lua
  game/view/widgethud.lua
Labels: UX, feature, interface

#769 Show cardinfo on picktarget and pickdir states
  game/domain/action.lua
  game/domain/builders/actor.lua
  game/domain/builders/card.lua
  game/domain/card.lua
  game/domain/maneuver/activate_widget.lua
  game/domain/maneuver/consume_cards_from_buffer.lua
  game/domain/maneuver/draw_new_hand.lua
  game/domain/maneuver/idle.lua
  game/domain/maneuver/interact.lua
  game/domain/maneuver/move.lua
  game/domain/maneuver/play_card.lua
  game/domain/maneuver/receive_pack.lua
  game/domain/maneuver/use_signature.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/gamestates/user_turn.lua
  game/view/cardinfo.lua
  game/view/hand.lua
Labels: UX

#770 Add ON_FOCUS_END trigger and set it on laser spear
  game/database/domains/card/laser-spear.json
  game/domain/actor.lua
  game/domain/definitions/triggers.lua
Labels: feature, gameplay

#775 Consuming cards provides XP distributed by attribute usage
  game/database/domains/card/ani_1.json
  game/database/domains/card/arc_1.json
  game/database/domains/card/cor_1.json
  game/database/domains/cardset/upgrades.json
  game/database/domains/cardset/upgrades_ani.json
  game/database/domains/cardset/upgrades_arc.json
  game/database/domains/cardset/upgrades_common.json
  game/database/domains/cardset/upgrades_cor.json
  game/database/domains/collection/anything.json
  game/database/schema/card.lua
  game/domain/actor.lua
  game/domain/builders/actor.lua
  game/domain/card.lua
  game/domain/definitions/init.lua
  game/domain/effects/upgrade_attribute.lua
  game/domain/inputs/card_is_type.lua
  game/domain/inputs/upgrade_cost.lua
  game/domain/inputs/upgrade_list.lua
  game/domain/maneuver/play_card.lua
  game/view/actor.lua
  game/view/consumelist.lua
  game/view/hand.lua
  game/view/helpers/card.lua
  game/view/helpers/exp.lua
Labels: feature, gameplay

#776 Remove action menu, change longwalk input
  game/gamestates/action_menu.lua
  game/gamestates/user_turn.lua
  game/main.lua
  game/view/actionmenu.lua
Labels: refactoring

#777 Added all cards as possible drops in packs + fix laser spear
  game/database/domains/card/bullet.json
  game/database/domains/card/calming_down.json
  game/database/domains/card/divination.json
  game/database/domains/card/dropkick.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/fix-turret.json
  game/database/domains/card/flash.json
  game/database/domains/card/focus.json
  game/database/domains/card/goggles.json
  game/database/domains/card/haste.json
  game/database/domains/card/heal.json
  game/database/domains/card/high-punch.json
  game/database/domains/card/illusion_of_darkness.json
  game/database/domains/card/impact-vest.json
  game/database/domains/card/jetboots.json
  game/database/domains/card/jump.json
  game/database/domains/card/laser-spear.json
  game/database/domains/card/meteor_blast.json
  game/database/domains/card/power-suit.json
  game/database/domains/card/push.json
  game/database/domains/card/rage.json
  game/database/domains/card/reassemble.json
  game/database/domains/card/reinforce.json
  game/database/domains/card/rush.json
  game/database/domains/card/rusty-blaster.json
  game/database/domains/card/seedling-sap.json
  game/database/domains/card/sensor-bomb.json
  game/database/domains/card/soul_robe.json
  game/database/domains/card/spark_rod.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/summon.json
  game/database/domains/card/teleport.json
  game/database/domains/card/timebomb-drone.json
  game/database/domains/card/wrench.json
  game/database/domains/cardset/arcanist.json
  game/database/domains/cardset/brawler.json
  game/database/domains/cardset/gadgeteer.json
  game/database/domains/collection/anything.json
Labels: content, gameplay

#778 Unequip weapon on focus end
  game/domain/actor.lua
Labels: feature

#779 Having no hand doesn't reset focus
  game/domain/actor.lua
Labels: feature, gameplay

#780 Balance transformers
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/domain/transformers/altars.lua
  game/domain/transformers/drops.lua
Labels: gameplay

#781 Improved pack and consumelist view
  game/assets/texture/pack.png
  game/view/cardlist.lua
  game/view/consumelist.lua
  game/view/packlist.lua
Labels: interface

#783 Rising text doesn't break line
  game/view/spritefx/text_rise.lua
Labels: bug, interface

#785 Some card tweaks
  game/database/domains/card/auto-fire.json
  game/database/domains/card/calming_down.json
  game/database/domains/card/fireball.json
  game/database/domains/card/focus.json
  game/database/domains/card/goggles.json
  game/database/domains/card/haste.json
  game/database/domains/card/impact-vest.json
  game/database/domains/card/jetboots.json
  game/database/domains/card/power-suit.json
  game/database/domains/card/proximity-detector.json
  game/database/domains/card/rusty-blaster.json
  game/database/domains/card/seedling-sap.json
  game/database/domains/card/tipsy.json
  game/domain/effects/damage_on_area.lua
Labels: content

#786 Equiping a widget leaves you with full focus
  game/domain/actor.lua
  game/view/hand.lua
Labels: feature, gameplay

#784 Added emergency effect on focus duration
  game/view/hand.lua
Labels: interface

#787 Added color to consumelist view attributes
  game/view/consumelist.lua
Labels: interface

#788 Uniformize fonts a little bit
  game/resources/init.lua
  game/view/cardlist.lua
  game/view/consumelist.lua
  game/view/packlist.lua
  game/view/pickwidget.lua
  game/view/readyability.lua
Labels: interface, minor

#791 Make jetboots an accessory
  game/database/domains/card/jetboots.json
Labels: content

#789 Fix widget duplication
  game/domain/body.lua
Labels: bug

#790 Scale cooldown bar proportionally to actor speed
  game/view/sector/cooldownbar.lua
Labels: UX
