Repository uspgamedev/backdoor, pull requests merged in 2018-03, with the labels that each got.

#587 Update IMGUI version + add demo window
  Makefile
  game/debug/gui.lua
Labels: devmode, feature

#588 Devmode code: improve naming
  game/debug/view/actor_inspector.lua
  game/debug/view/actors_menu.lua
  game/debug/view/bodies_menu.lua
  game/debug/view/body_inspector.lua
  game/debug/view/category_list.lua
  game/debug/view/input/ability.lua
  game/debug/view/input/array.lua
  game/debug/view/input/common.lua
  game/debug/view/input/enum.lua
  game/debug/view/input/init.lua
  game/debug/view/input/list.lua
  game/debug/view/input/reference.lua
  game/debug/view/input/section.lua
  game/debug/view/input/vector.lua
  game/debug/view/list_picker.lua
  game/debug/view/name_input.lua
  game/debug/view/specification_editor.lua
Labels: devmode, refactoring

#602 Fix IMGUI return order
  game/debug/gui.lua
Labels: bug, devmode

#606 Long walk
  game/database/settings/controls.json
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
Labels: UX, feature

#610 Fix Focus Gem
  game/database/domains/card/focus.json
  game/domain/inputs/card_is_type.lua
  game/domain/inputs/different_card.lua
Labels: bug, content

#611 Holdbar accepts now numeours hold actions
  game/gamestates/manage_buffer.lua
  game/gamestates/open_pack.lua
  game/view/cardlist.lua
  game/view/helpers/holdbar.lua
  game/view/packlist.lua
Labels: UX, feature

#612 Change "pierced damage" to "life loss"
  game/database/domains/card/dropkick.json
  game/domain/body.lua
  game/domain/effects/lose_life.lua
Labels: gameplay, refactoring

#616 Remove obsolete fields from devmode's abilities
  game/debug/view/input/ability.lua
Labels: bug, devmode
