Repository uspgamedev/backdoor, pull requests merged in 2018-12, with the labels that each got.

#972 Add search field for DB categories
  game/devmode/view/category_list.lua
Labels: devmode

#973 Created helper files for longwalk and adjacency methods for Action HUD
  game/view/action_hud.lua
  game/view/helpers/adjacency.lua
  game/view/helpers/long_walk.lua
Labels: refactoring

#975 Fixed crash when using some attacks
  game/database/resources/sfx/attack-hit.json
Labels: bug

#977 Fixed adjacency and longwalk stuff that was missing
  game/view/action_hud.lua
  game/view/helpers/adjacency.lua
  game/view/helpers/long_walk.lua
Labels: bug

#980 Fix holdbar locks + cleaned the code
  game/database/domains/card/rush.json
  game/gamestates/open_pack.lua
  game/gamestates/pick_target.lua
  game/view/action_hud.lua
  game/view/packlist.lua
Labels: bug, refactoring

#983 Added setLooping and stopAll method for Sources
  game/resources/sfx.lua
  game/view/playerdeath.lua
Labels: bug

#984 Icons are now white and can be easily colored on love
  game/assets/texture/auto-repair.png
  game/assets/texture/boot-stomp.png
  game/assets/texture/boots.png
  game/assets/texture/brandy-bottle.png
  game/assets/texture/burning-dot.png
  game/assets/texture/burning-meteor.png
  game/assets/texture/card-goggles.png
  game/assets/texture/card-turret.png
  game/assets/texture/chest-armor.png
  game/assets/texture/emerald.png
  game/assets/texture/fire-dash.png
  game/assets/texture/fire-punch.png
  game/assets/texture/fire-silhouette.png
  game/assets/texture/fission.png
  game/assets/texture/fluffy-flame.png
  game/assets/texture/hospital-cross.png
  game/assets/texture/land-mine.png
  game/assets/texture/lunar-wand.png
  game/assets/texture/magic-trident.png
  game/assets/texture/meditation.png
  game/assets/texture/metal-scales.png
  game/assets/texture/monkey-wrench.png
  game/assets/texture/no-icon.png
  game/assets/texture/orb-direction.png
  game/assets/texture/ray-gun.png
  game/assets/texture/robe.png
  game/assets/texture/square-bottle.png
  game/assets/texture/teleport.png
  game/assets/texture/time-bomb.png
  game/assets/texture/triorb.png
  game/assets/texture/upgrade.png
  game/assets/texture/warlock-eye.png
  game/assets/texture/wide-arrow-dunk.png
  game/view/packlist.lua
Labels: graphics
