Repository uspgamedev/backdoor, pull requests merged in 2018-11, with the labels that each got.

#951 'HELP' button ('select' / 'lshift') now shows control hints buttons
  game/database/settings/controls.json
  game/view/action_hud.lua
  game/view/buffer.lua
  game/view/controlhints/changehandcursor.lua
  game/view/controlhints/controlhint.lua
  game/view/controlhints/newhand.lua
  game/view/hand.lua
Labels: UX, feature

#954 Transmissions bend like crazy
  game/view/transmission.lua
Labels: UX, juice

#950 Refactor actor hud
  game/gamestates/play.lua
  game/view/actorpanel/attr.lua
  game/view/actorpanel/init.lua
  game/view/actorpanel/lifebar.lua
  game/view/actorpanel/minimap.lua
  game/view/actorpanel/ppbar.lua
  game/view/actorpanel/stats/attribute.lua
  game/view/actorpanel/stats/init.lua
  game/view/actorpanel/widgets/init.lua
  game/view/actorpanel/widgets/slot.lua
  game/view/consumelist.lua
  game/view/helpers/text.lua
  game/view/node.lua
Labels: refactoring

#965 Randomly invert the initial angle of bendings
  game/view/transmission.lua
Labels: juice

#967 Debug -> devmode
  game/README.md
  game/devmode/gui.lua
  game/devmode/view/actor_inspector.lua
  game/devmode/view/actors_menu.lua
  game/devmode/view/bodies_menu.lua
  game/devmode/view/body_inspector.lua
  game/devmode/view/category_list.lua
  game/devmode/view/helpers/integer.lua
  game/devmode/view/helpers/string.lua
  game/devmode/view/input/ability.lua
  game/devmode/view/input/array.lua
  game/devmode/view/input/common.lua
  game/devmode/view/input/enum.lua
  game/devmode/view/input/init.lua
  game/devmode/view/input/list.lua
  game/devmode/view/input/reference.lua
  game/devmode/view/input/section.lua
  game/devmode/view/input/vector.lua
  game/devmode/view/list_picker.lua
  game/devmode/view/name_input.lua
  game/devmode/view/specification_editor.lua
  game/gamestates/play.lua
Labels: devmode, refactoring

#968 Use forgotten sfx for attack
  game/database/domains/card/trained-strike.json
  game/database/resources/sfx/attack-hit.json
Labels: music/sound

#957 Sound/polyphony
  game/database/resources/sfx/back-menu.json
  game/database/resources/sfx/change-sector.json
  game/database/resources/sfx/death-crumble.json
  game/database/resources/sfx/denied.json
  game/database/resources/sfx/equip-break.json
  game/database/resources/sfx/example.json
  game/database/resources/sfx/footstep.json
  game/database/resources/sfx/get-item.json
  game/database/resources/sfx/holdbar-charge.json
  game/database/resources/sfx/holdbar-confirm.json
  game/database/resources/sfx/ok-menu.json
  game/database/resources/sfx/open-menu.json
  game/database/resources/sfx/select-menu.json
  game/database/resources/sfx/teleport.json
  game/database/resources/sfx/transmission.json
  game/database/resources/sfx/upgrade.json
  game/database/schema/sfx.lua
  game/helpers/playsfx.lua
  game/resources/init.lua
Labels: music/sound

#969 Aligned exp preview with exp text
  game/view/actorpanel/stats/init.lua
  game/view/helpers/text.lua
Labels: UX, minor

#970 Consume list won't appear above actor panel anymore
  game/draw.lua
  game/gamestates/consume_cards.lua
  game/setup.lua
Labels: UX, bug
