Repository uspgamedev/backdoor, pull requests merged in 2018-10, with the labels that each got.

#925 Slight offset + circles at ends of transmission
  game/view/transmission.lua
Labels: UX

#934 "Closing animation" for announcement
  game/gamestates/user_turn.lua
  game/view/announcement.lua
  game/view/helpers/tweenvalue.lua
Labels: juice

#940 Integrate a promise-like "Deferred" to task yielding
  game/common/activity.lua
  game/common/deferred.lua
  game/view/announcement.lua
  game/view/helpers/tweenvalue.lua
Labels: refactoring

#942 Holdbar has ton of particles
  game/view/helpers/holdbar.lua
Labels: UX, juice

#943 New sprite for hillborn
  game/assets/texture/hillborn-idle.png
  game/database/resources/sprite/hillborn-idle.json
  workbench/hearthborn-idle.ase
  workbench/hillborn-a-take2-01.ase
  workbench/hillborn-a-take2-02.ase
  workbench/hillborn-a-take2-03.ase
Labels: graphics

#947 Buttons for moving hand cursor and drawing new hand
  game/assets/texture/Ouya_L1.png
  game/assets/texture/Ouya_L2.png
  game/assets/texture/Ouya_R1.png
  game/assets/texture/Ouya_R2.png
  game/assets/texture/PS4_Circle.png
  game/assets/texture/PS4_Cross.png
  game/assets/texture/PS4_Square.png
  game/assets/texture/PS4_Triangle.png
  game/database/resources/texture/button-draw_hand.json
  game/database/resources/texture/button-next_hand_cursor.json
  game/database/resources/texture/button-prev_hand_cursor.json
  game/view/action_hud.lua
  game/view/buffer.lua
  game/view/hand.lua
Labels: UX

#953 Remove unused menu
  game/debug/gui.lua
Labels: devmode

#945 Don't show holdbar when out of pp
  game/view/action_hud.lua
  game/view/helpers/holdbar.lua
Labels: UX
