Repository uspgamedev/backdoor, pull requests merged in 2018-09, with the labels that each got.

#873 Keep your hands up
  game/gamestates/card_select.lua
  game/gamestates/user_turn.lua
  game/view/hand.lua
Labels: UX, interface

#876 Announcement with transmissions
  game/assets/texture/buffer_flat.png
  game/database/resources/texture/buffer-flat.json
  game/domain/definitions/colors.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/view/announcement.lua
  game/view/buffer.lua
  game/view/card.lua
  game/view/focusbar.lua
  game/view/hand.lua
  game/view/transmission.lua
Labels: UX, interface, juice

#874 Fix accidental globals
  game/common/visibility.lua
  game/domain/transformers/helpers/sectorgrid.lua
  game/gamestates/user_turn.lua
  game/main.lua
  game/view/actor/minimap.lua
  game/view/consumelist.lua
  game/view/packlist.lua
  game/view/sector.lua
  game/view/sector/tilemap.lua
  game/view/spritefx/body_acted.lua
Labels: minor, refactoring

#886 Make VFX wait announcement lock
  game/view/announcement.lua
  game/view/card.lua
  game/view/sector.lua
Labels: UX, interface, juice

#890 Card description box
  game/gamestates/card_select.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/view/cardinfo.lua
  game/view/hand.lua
  game/view/helpers/newhand_card.lua
  game/view/sector.lua
Labels: UX, juice

#900 Gameover animation state
  game/assets/sfx/deathwhite.wav
  game/database/resources/sfx/death-crumble.json
  game/gamestates/gameover.lua
  game/gamestates/play.lua
  game/view/playerdeath.lua
Labels: feature, interface, music/sound

#901 Improved menu logo
  .gitignore
  game/assets/texture/logo-bg1.png
  game/assets/texture/logo-bg10.png
  game/assets/texture/logo-bg11.png
  game/assets/texture/logo-bg2.png
  game/assets/texture/logo-bg3.png
  game/assets/texture/logo-bg4.png
  game/assets/texture/logo-bg5.png
  game/assets/texture/logo-bg6.png
  game/assets/texture/logo-bg7.png
  game/assets/texture/logo-bg8.png
  game/assets/texture/logo-bg9.png
  game/assets/texture/logo-text.png
  game/database/resources/texture/logo-bg1.json
  game/database/resources/texture/logo-bg10.json
  game/database/resources/texture/logo-bg11.json
  game/database/resources/texture/logo-bg2.json
  game/database/resources/texture/logo-bg3.json
  game/database/resources/texture/logo-bg4.json
  game/database/resources/texture/logo-bg5.json
  game/database/resources/texture/logo-bg6.json
  game/database/resources/texture/logo-bg7.json
  game/database/resources/texture/logo-bg8.json
  game/database/resources/texture/logo-bg9.json
  game/database/resources/texture/logo-text.json
  game/gamestates/start_menu.lua
  game/view/startmenu.lua
Labels: graphics

#895 Hide hand and focus bar outside user turn
  game/draw.lua
  game/gamestates/card_select.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/view/card.lua
  game/view/focusbar.lua
  game/view/hand.lua
  game/view/hud_animator.lua
Labels: UX, juice

#903 Add title menu theme
  game/assets/bgm/backdoor_menuv2.ogg
  game/assets/bgm/backdoor_menuv3.ogg
  game/database/resources/bgm/title-menu.json
  game/gamestates/play.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
  game/view/soundtrack/init.lua
Labels: music/sound

#907 Fixed bug when playing music themes in play state
  game/gamestates/play.lua
Labels: bug

#909 Action HUD interaction
  game/draw.lua
  game/gamestates/card_select.lua
  game/gamestates/hud_animation.lua
  game/gamestates/play.lua
  game/gamestates/ready_ability.lua
  game/gamestates/user_turn.lua
  game/view/action_hud.lua
  game/view/card.lua
  game/view/cardinfo.lua
  game/view/hand.lua
  game/view/helpers/card.lua
  game/view/hud_animator.lua
Labels: UX, interface, refactoring

#921 Fix #919
  game/gamestates/play.lua
Labels: bug

#920 Fix #918
  game/view/action_hud.lua
Labels: bug

#922 Confirmation holdbar for focus mode
  game/view/action_hud.lua
  game/view/consumelist.lua
  game/view/helpers/holdbar.lua
  game/view/packlist.lua
Labels: UX, interface

#927 Start with focusbar hidden
  game/view/focusbar.lua
Labels: UX, bug

#928 Destroying actionhud on death
  game/gamestates/play.lua
Labels: UX

#931 Keep hands up when changing widget
  game/gamestates/user_turn.lua
Labels: UX

#932 Lock user input when lowering hand
  game/view/action_hud.lua
Labels: UX

#930 Play SFX in transmission FX
  game/database/resources/sfx/transmission.json
  game/view/transmission.lua
Labels: music/sound

#933 Altar now displays cards in alphanumeric order
  game/domain/actor.lua
  game/domain/maneuver/consume_cards_from_buffer.lua
  game/gamestates/user_turn.lua
  game/view/consumelist.lua
Labels: UX
