Repository uspgamedev/backdoor, pull requests merged in 2018-05, with the labels that each got.

#685 Zone domain
  game/common/graph.lua
  game/database/domains/zone/ruins.json
  game/database/domains/zone/seed1.json
  game/database/domains/zone/seed2.json
  game/database/domains/zone/seed3.json
  game/database/domains/zone/seed4.json
  game/database/domains/zone/seed5.json
  game/database/domains/zone/seed6.json
  game/database/domains/zone/seed7.json
  game/database/domains/zone/seed8.json
  game/database/domains/zone/zone1.json
  game/database/domains/zone/zone2.json
  game/database/domains/zone/zone3.json
  game/database/domains/zone/zone4.json
  game/database/schema/zone.lua
  game/debug/gui.lua
  game/domain/builders/sectors.lua
  game/domain/definitions/regions.lua
  game/domain/route.lua
  game/domain/sector.lua
  game/domain/transformers/bootstrap.lua
  game/view/actor.lua
Labels: feature

#688 Load 'generated' flag from sector
  game/domain/sector.lua
Labels: bug

#691 Make BGM loop
  game/resources/init.lua
Labels: art, bug

#690 Make wall semitransparent if there is a body behind it
  game/domain/definitions/colors.lua
  game/view/sector.lua
Labels: UX, feature

#692 Add upgrade exp cost to card helper
  game/view/helpers/card.lua
Labels: feature

#700 Refactor lifebar and cooldown to be mirrored
  game/view/sector.lua
  game/view/sector/cooldownbar.lua
  game/view/sector/lifebar.lua
Labels: interface, juice

#703 Add sparkle particles
  game/view/sector.lua
Labels: feature

#705 Add display of fps for debbuging purposes
  game/setup.lua
  game/view/actor.lua
  game/view/sector/wall.lua
Labels: interface, minor

#706 Enhance longwalk
  game/domain/actor.lua
  game/gamestates/animation.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
Labels: UX, feature

#710 Feature: range input
  game/database/schema/actor.lua
  game/debug/view/input/common.lua
Labels: devmode, feature

#720 Remove control menu if DEV flag not on
  game/gamestates/start_menu.lua
Labels: feature
