Repository uspgamedev/backdoor, pull requests merged in 2018-04, with the labels that each got.

#623 Refactor colors and sector view in parts
  game/assets/texture/pixel.png
  game/common/camera.lua
  game/common/color.lua
  game/database/resources/texture/pixel.json
  game/domain/definitions/colors.lua
  game/view/definitions/init.lua
  game/view/sector.lua
  game/view/sector/tilemap.lua
Labels: refactoring

#624 Features/factions
  game/database/domains/body/corgi.json
  game/database/domains/body/demihuman.json
  game/database/domains/body/eye.json
  game/database/domains/body/hearthborn.json
  game/database/domains/body/hillborn.json
  game/database/domains/body/imp.json
  game/database/domains/body/machine.json
  game/database/domains/body/rewasvat.json
  game/database/domains/body/slime.json
  game/database/domains/faction/agressive.json
  game/database/domains/faction/allied.json
  game/database/schema/body.lua
  game/database/schema/faction.lua
  game/debug/gui.lua
  game/domain/body.lua
  game/domain/inputs/choose_target.lua
Labels: feature

#638 Make heal target self position, add require to pickwidget view, fix sector size
  game/database/domains/card/heal.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/view/pickwidget.lua
Labels: UX, bug, minor

#639 Enhance monster behavior
  game/database/domains/card/teleport.json
  game/debug/view/actor_inspector.lua
  game/debug/view/body_inspector.lua
  game/domain/actor.lua
  game/domain/behaviors/aggro.lua
  game/domain/behaviors/helpers/findpath.lua
  game/domain/behaviors/helpers/random.lua
  game/view/sector.lua
  game/view/sector/tilemap.lua
Labels: bug, devmode, feature, gameplay, refactoring

#637 Do not close menu if action is invalid
  game/gamestates/user_turn.lua
  game/view/pickwidget.lua
Labels: UX

#643 Optimize two parts of monster behavior
  game/domain/actor.lua
  game/view/sector.lua
  game/view/spritefx/body_moved.lua
Labels: refactoring

#644 Refactor number VFX
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/heal.lua
  game/domain/effects/lose_life.lua
  game/domain/effects/reward_pp.lua
  game/gamestates/play.lua
  game/view/spritefx/dmg_taken.lua
  game/view/spritefx/healed.lua
  game/view/spritefx/number_rise.lua
Labels: refactoring

#645 Feature: drops transformer
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/database/schema/sector.lua
  game/domain/sector.lua
  game/domain/transformers/drops.lua
Labels: feature

#646 Make action menu cycle
  game/gamestates/action_menu.lua
  game/view/actionmenu.lua
Labels: UX, interface

#650 Collect drops at start of turn, while turn is still actor's
  game/domain/actor.lua
  game/domain/sector.lua
Labels: UX, bug

#649 Fix hold direction persisting after consuming card
  game/infra/dir.lua
Labels: UX, bug

#651 Fix start menu locking glitch and Add slight black time before starting route
  game/gamestates/play.lua
  game/gamestates/start_menu.lua
Labels: bug

#655 Target finders may ignore same faction
  game/database/domains/card/auto-fire.json
  game/domain/inputs/has_nearby_bodies.lua
  game/domain/operators/find_nearest_body.lua
Labels: bug

#653 Use coroutine-based tasks for callbacks
  game/common/activity.lua
  game/gamestates/play.lua
Labels: refactoring

#656 Refactor routebuild
  game/common/random.lua
  game/domain/definitions/routebuilddata.lua
  game/infra/routebuilder.lua
Labels: minor, refactoring

#658 Refactor start menu to use activity module
  game/gamestates/start_menu.lua
Labels: refactoring

#661 SFX
  game/assets/sfx/Footstep.wav
  game/assets/sfx/Teleport.wav
  game/assets/sfx/Upgrade2.wav
  game/assets/sfx/back_menu.wav
  game/assets/sfx/denied.wav
  game/assets/sfx/get_item.wav
  game/assets/sfx/going_down_stars.wav
  game/assets/sfx/ok_menu.wav
  game/assets/sfx/open_menu.wav
  game/assets/sfx/select_menu.wav
  game/database/domains/card/teleport.json
  game/database/resources/sfx/back-menu.json
  game/database/resources/sfx/change-sector.json
  game/database/resources/sfx/denied.json
  game/database/resources/sfx/footstep.json
  game/database/resources/sfx/get-item.json
  game/database/resources/sfx/ok-menu.json
  game/database/resources/sfx/open-menu.json
  game/database/resources/sfx/select-menu.json
  game/database/resources/sfx/teleport.json
  game/database/resources/sfx/upgrade.json
  game/database/schema/body.lua
  game/domain/actor.lua
  game/domain/effects/move_to.lua
  game/domain/maneuver/move.lua
  game/domain/maneuver/play_card.lua
  game/gamestates/action_menu.lua
  game/gamestates/card_select.lua
  game/gamestates/manage_buffer.lua
  game/gamestates/open_pack.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/gamestates/pick_widget_slot.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/helpers/playsfx.lua
  game/view/sector.lua
Labels: UX

#663 AI persisting state
  game/domain/actor.lua
  game/domain/behaviors/aggro.lua
  game/domain/behaviors/helpers/findtarget.lua
  game/domain/behaviors/helpers/randomwalk.lua
  game/domain/behaviors/init.lua
  game/domain/route.lua
  game/domain/sector.lua
  game/infra/routebuilder.lua
Labels: feature

#665 New drop type: card pack
  game/assets/texture/box-pack.png
  game/database/domains/drop/pack.json
  game/database/domains/sector/sector01.json
  game/database/resources/texture/pack-drop.json
  game/domain/ability.lua
  game/domain/effects/give_pack.lua
  game/domain/inputs/is_controlled_actor.lua
Labels: content, feature, gameplay

#669 Spread drops
  game/domain/sector.lua
  game/view/sector.lua
  game/view/spritefx/body_moved.lua
  game/view/spritefx/drop_spread.lua
Labels: feature, juice

#667 Play sfx only when seeing
  game/domain/maneuver/play_card.lua
  game/view/sector.lua
Labels: bug

#668 Add permanent widgets
  game/database/domains/card/soul_robe.json
  game/database/schema/card.lua
  game/domain/body.lua
  game/domain/card.lua
  game/view/helpers/widget.lua
Labels: feature

#680 Cooldown HUD and preview
  game/database/domains/card/firebolt.json
  game/domain/action.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/maneuver/activate_widget.lua
  game/domain/maneuver/consume_cards_from_buffer.lua
  game/domain/maneuver/draw_new_hand.lua
  game/domain/maneuver/idle.lua
  game/domain/maneuver/interact.lua
  game/domain/maneuver/move.lua
  game/domain/maneuver/play_card.lua
  game/domain/maneuver/receive_pack.lua
  game/domain/maneuver/use_signature.lua
  game/gamestates/user_turn.lua
  game/view/sector.lua
  game/view/sector/cooldownbar.lua
Labels: UX, juice

#681 Make route be generated as a graph
  game/common/graph.lua
  game/database/settings/init_tiledata.json
  game/domain/builders/actor.lua
  game/domain/builders/body.lua
  game/domain/builders/buffers.lua
  game/domain/builders/route.lua
  game/domain/builders/sectors.lua
  game/domain/definitions/regions.lua
  game/domain/definitions/routebuilddata.lua
  game/domain/definitions/routemap.lua
  game/domain/maneuver/interact.lua
  game/domain/route.lua
  game/domain/sector.lua
  game/domain/transformers/exits.lua
  game/infra/profile.lua
  game/infra/routebuilder.lua
  game/main.lua
  game/tests/init.lua
  game/tests/routegen.lua
Labels: feature, refactoring
