Repository uspgamedev/backdoor, pull requests merged in 2018-08, with the labels that each got.

#793 Refactor gamestate manager to allow update on drawables
  game/draw.lua
  game/gamestates/animation.lua
  game/gamestates/card_select.lua
  game/gamestates/character_build.lua
  game/gamestates/consume_cards.lua
  game/gamestates/manage_buffer.lua
  game/gamestates/open_pack.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/gamestates/pick_widget_slot.lua
  game/gamestates/play.lua
  game/gamestates/ready_ability.lua
  game/gamestates/start_menu.lua
  game/gamestates/user_turn.lua
  game/infra/profile.lua
  game/infra/switcher.lua
  game/main.lua
Labels: feature, refactoring

#794 Fix custom input methods for gamestates
  game/infra/switcher.lua
Labels: bug

#797 Fix deletion/saving when renaming specs in DB
  game/database/init.lua
  game/debug/view/category_list.lua
Labels: devmode, feature

#798 Do not use mysterious global "actor"
  game/debug/view/body_inspector.lua
Labels: bug, devmode

#800 Fix mysterious global actor source
  game/domain/sector.lua
Labels: bug

#802 Balance Blind and Push
  game/database/domains/card/blind.json
  game/database/domains/card/push.json
Labels: content, gameplay

#845 Add a deploy parameter for build type (stable, nightly, etc.)
  Makefile
Labels: devops

#847 Automate gamestate loading
  game/gamestates/init.lua
  game/main.lua
Labels: refactoring

#852 Refactor makefile targets to build imgui
  Makefile
Labels: devops

#853 Linux build & deploy
  Makefile
Labels: devops

#848 Settings Menu
  game/database/settings/user-preferences.json
  game/domain/definitions/colors.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
  game/helpers/playsfx.lua
  game/infra/profile.lua
  game/view/settings.lua
  game/view/soundtrack/init.lua
Labels: feature, interface

#858 Fix profile user preferences not being loaded
  game/infra/profile.lua
Labels: bug

#860 Change scroll threshold to 6
  game/view/startmenu.lua
Labels: interface

#867 Do not hide hand after using draw hand "card"
  game/gamestates/card_select.lua
  game/gamestates/user_turn.lua
Labels: UX

#864 Use love's new setget CRequirePath methods
  game/libs/init.lua
Labels: minor, refactoring

#866 Keep dead saves
  game/domain/route.lua
  game/domain/sector.lua
  game/gamestates/play.lua
  game/gamestates/start_menu.lua
  game/infra/profile.lua
  game/infra/writingthread.lua
Labels: feature, refactoring

#869 Card transmission visual effect
  game/gamestates/card_select.lua
  game/view/buffer.lua
  game/view/card.lua
  game/view/consumelist.lua
  game/view/hand.lua
  game/view/transmission.lua
Labels: UX, interface

#870 Refactor draw layers
  game/draw.lua
  game/gamestates/play.lua
  game/setup.lua
  game/view/focusbar.lua
  game/view/hand.lua
Labels: UX, interface, refactoring
