Repository uspgamedev/backdoor, pull requests merged in 2019-08, with the labels that each got.

#1051 Fix #879
  game/common/visibility.lua
  game/domain/actor.lua
  game/view/sector/tilemap.lua
  game/view/sector/wall.lua
Labels: bug, graphics

#1053 [PROPOSAL] Energy system instead of cooldown system
  game/database/domains/action/bolting.json
  game/database/domains/action/bullet.json
  game/database/domains/action/glare.json
  game/database/domains/action/punch.json
  game/database/domains/action/scratch.json
  game/database/domains/action/tackle.json
  game/database/domains/card/bolting.json
  game/database/domains/card/bullet.json
  game/database/domains/card/consume.json
  game/database/domains/card/divination.json
  game/database/domains/card/dropkick.json
  game/database/domains/card/energy-beam.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/fix-turret.json
  game/database/domains/card/flash.json
  game/database/domains/card/haste.json
  game/database/domains/card/heal.json
  game/database/domains/card/healing_potion.json
  game/database/domains/card/illusion_of_darkness.json
  game/database/domains/card/jump.json
  game/database/domains/card/laser-spear.json
  game/database/domains/card/meteor_blast.json
  game/database/domains/card/punch.json
  game/database/domains/card/push.json
  game/database/domains/card/reassemble.json
  game/database/domains/card/reinforce.json
  game/database/domains/card/rush.json
  game/database/domains/card/sensor-bomb.json
  game/database/domains/card/spark_rod.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/teleport.json
  game/database/domains/card/timebomb-drone.json
  game/database/domains/card/trained-strike.json
  game/database/domains/card/turret.json
  game/database/domains/card/wrench.json
  game/database/schema/action.lua
  game/database/schema/card.lua
  game/domain/actor.lua
  game/domain/builders/actor.lua
  game/domain/definitions/action.lua
  game/domain/definitions/attribute.lua
  game/gamestates/user_turn.lua
  game/tests/interface.lua
  game/view/sector.lua
  game/view/sector/energybar.lua
Labels: feature, gameplay

#1068 Improved consume list view
  game/view/consumelist.lua
  game/view/helpers/holdbar.lua
  game/view/packlist.lua
Labels: interface

#1069 Removes diagonals for movement
  game/database/settings/controls.json
  game/domain/behaviors/helpers/randomwalk.lua
  game/domain/definitions/dir.lua
  game/infra/dir.lua
  game/view/sector.lua
Labels: UX, refactoring

#1071 Remove diagonals for effects range checks
  game/common/tile.lua
  game/domain/effects/damage_on_area.lua
  game/view/sector.lua
Labels: UX, gameplay, refactoring

#1073 Reduce stamina scale
  game/database/domains/drop/food.json
  game/database/domains/drop/food2.json
  game/domain/body.lua
  game/domain/definitions/init.lua
Labels: gameplay

#1075 Removed diagonals from fov logic
  game/common/visibility.lua
  game/view/sector/tilemap.lua
Labels: interface, refactoring

#1078 Card Info shows faster when hovering over a card
  game/view/action_hud.lua
Labels: UX, refactoring

#1082 Fix card info
  game/domain/card.lua
Labels: bug

#1083 Fix turret's card set
  game/database/domains/card/turret.json
  game/database/domains/card/wrench.json
Labels: bug

#1081 Lock pack size to 5
  game/domain/definitions/init.lua
  game/domain/pack.lua
Labels: gameplay

#1086 Fix #1076
  game/domain/actor.lua
Labels: bug, gameplay

#1087 Tweaked frequency of altars and packs
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
Labels: gameplay

#1084 Improve focus cost and charge display
  game/view/card.lua
Labels: interface

#1091 Close #1085
  game/gamestates/user_turn.lua
  game/view/action_hud.lua
  game/view/focusbar.lua
  game/view/hand.lua
  game/view/sector.lua
Labels: UX, interface

#1096 Improved focus icon
  game/assets/texture/focus-icon.png
  game/database/resources/texture/focus-icon.json
  game/view/card.lua
  game/view/focusbar.lua
Labels: graphics

#1097 Card info only shows after drawing all your hand
  game/gamestates/animations/draw_card.lua
  game/view/action_hud.lua
Labels: UX, minor

#1093 Less equipment types
  game/assets/texture/icon-wieldable.png
  game/database/domains/card/auto-fire.json
  game/database/domains/card/battery.json
  game/database/domains/card/blind.json
  game/database/domains/card/calming_down.json
  game/database/domains/card/catalyst.json
  game/database/domains/card/goggles.json
  game/database/domains/card/haste.json
  game/database/domains/card/impact-vest.json
  game/database/domains/card/jetboots.json
  game/database/domains/card/laser-spear.json
  game/database/domains/card/power-suit.json
  game/database/domains/card/proximity-detector.json
  game/database/domains/card/rage.json
  game/database/domains/card/reinforced-surface.json
  game/database/domains/card/rusty-blaster.json
  game/database/domains/card/self-destruct.json
  game/database/domains/card/slow.json
  game/database/domains/card/soul_robe.json
  game/database/domains/card/spark_rod.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stunned.json
  game/database/domains/card/wrench.json
  game/database/resources/texture/icon-wearable.json
  game/database/resources/texture/icon-wieldable.json
  game/database/schema/card.lua
  game/domain/body.lua
  game/domain/card.lua
  game/domain/definitions/equipments.lua
  game/domain/definitions/placements.lua
  game/view/actor/widgets.lua
  game/view/actorpanel/widgets/init.lua
  game/view/actorpanel/widgets/slot.lua
Labels: interface, refactoring

#1102 Fix leaking focus icons
  game/view/card.lua
Labels: bug

#1101 Blue for stamina
  game/domain/definitions/colors.lua
Labels: graphics

#1104 Side-step: new brawler basic card
  game/assets/texture/journey.png
  game/database/domains/actor/brawler.json
  game/database/domains/card/sidestep.json
  game/database/resources/texture/card-sidestep.json
Labels: content, gameplay

#1103 Refactor enemy drop rates
  game/database/domains/body/corgi.json
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
  game/database/domains/card/calming_down.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector_final.json
Labels: gameplay

#1105 Added icon for energy beam card
  game/assets/texture/ringed-beam.png
  game/database/domains/card/energy-beam.json
  game/database/resources/texture/card-energy-beam.json
Labels: graphics

#1108 [WIP] Refactored dialogue in initial sector
  game/database/domains/body/npc-adult-1.json
  game/database/domains/body/npc-adult-2.json
  game/database/domains/body/npc-adult-3.json
  game/database/domains/body/npc-elder-1.json
  game/database/domains/body/npc-elder-2.json
  game/database/domains/body/npc-farewell.json
  game/database/domains/body/npc-kid-1.json
  game/database/domains/body/npc-kid-2.json
  game/database/domains/body/npc-veteran-1.json
  game/database/domains/body/npc-veteran-2.json
  game/database/domains/body/npc-welcome.json
  game/view/dialoguebox.lua
Labels: UX, refactoring

#1110 Refactor initial sector
  game/database/domains/body/npc-adult-1.json
  game/database/domains/body/npc-adult-2.json
  game/database/domains/body/npc-adult-3.json
  game/database/domains/body/npc-elder-1.json
  game/database/domains/body/npc-elder-2.json
  game/database/domains/body/npc-farewell.json
  game/database/domains/body/npc-kid-1.json
  game/database/domains/body/npc-kid-2.json
  game/database/domains/body/npc-veteran-1.json
  game/database/domains/body/npc-veteran-2.json
  game/database/domains/body/npc-veteran-3.json
  game/database/domains/body/npc-welcome.json
  game/database/domains/sector/initial.json
  game/view/dialoguebox.lua
Labels: UX, gameplay

#1111 Added name to latest veteran created
  game/database/domains/body/npc-veteran-3.json
Labels: minor

#1112 Changed packed size to 3
  game/domain/definitions/init.lua
Labels: minor
