Repository uspgamedev/backdoor, pull requests merged in 2019-09, with the labels that each got.

#1123 Removed all traces of widget activation commands
  game/database/settings/controls.json
  game/gamestates/start_menu.lua
  game/gamestates/user_turn.lua
  game/view/action_hud.lua
Labels: bug

#1130 Improve card description
  game/domain/card.lua
Labels: UX, interface

#1128 Remove old armor mechanics, close #1124
  game/database/domains/card/reinforce.json
  game/database/domains/card/reinforced-surface.json
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/effects/armor_on_target.lua
  game/view/actor.lua
  game/view/sector/lifebarbatch.lua
  game/view/spritefx/text_rise.lua
Labels: refactoring

#1129 Draw action cards after hand cards
  game/domain/actor.lua
  game/domain/card.lua
  game/domain/maneuver/draw_new_hand.lua
Labels: UX

#1131 Kill card view mid-transmission
  game/gamestates/animations/play_card.lua
  game/view/action_hud.lua
Labels: UX

#1132 Temporary Cards
  game/assets/texture/temporary_card.png
  game/database/domains/card/laser-cut.json
  game/database/domains/card/sidestep.json
  game/database/resources/texture/temporary-card-base.json
  game/database/schema/card.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/card.lua
  game/gamestates/animations/discard_temporary_card.lua
  game/gamestates/animations/play_card.lua
  game/view/card.lua
  game/view/dissolvecard.lua
  game/view/hand.lua
  game/view/transmission.lua
Labels: feature

#1151 Hand backpanel + aligned cards
  game/view/hand.lua
Labels: interface

#1152 Reshape and rise focus bar
  game/view/card.lua
  game/view/focusbar.lua
Labels: interface

#1155 Close #1138
  game/view/cardinfo.lua
  game/view/definitions/init.lua
  game/view/hand.lua
Labels: interface

#1158 New buffer view
  game/assets/texture/buffer.png
  game/view/buffer.lua
Labels: interface

#1160 Draw card icon in description view
  game/view/cardinfo.lua
Labels: interface

#1163 Smooth movement for focused card
  game/view/card.lua
Labels: interface, minor

#1164 Better discard animation
  game/database/domains/card/sidestep.json
  game/database/domains/card/trained-strike.json
  game/domain/actor.lua
  game/gamestates/animations/discard_card.lua
  game/gamestates/animations/discard_temporary_card.lua
  game/gamestates/animations/draw_card.lua
  game/view/buffer.lua
Labels: interface, juice

#1166 Fix ghost hud
  game/view/gameplay/actionhud/hand/init.lua
  game/view/gameplay/actionhud/init.lua
Labels: bug

#1168 Backbuffer is shuffled into front buffer when drawing from empty buffer
  game/domain/actor.lua
  game/gamestates/animations/shuffle_buffers.lua
  game/view/buffer.lua
Labels: interface

#1167 Fix weapon action cards
  game/domain/actor.lua
  game/gamestates/animations/create_equipment_card.lua
Labels: bug

#1173 Dissolve one time art cards
  game/gamestates/animations/play_art_card.lua
Labels: UX

#1172 Keep cardinfo visible during card animations
  game/domain/maneuver/play_card.lua
  game/gamestates/animations/play_art_card.lua
  game/gamestates/animations/play_widget_card.lua
  game/view/gameplay/actionhud/hand/cardinfo.lua
  game/view/gameplay/actionhud/hand/init.lua
  game/view/gameplay/actionhud/init.lua
Labels: UX
