Repository uspgamedev/backdoor, pull requests merged in 2019-11, with the labels that each got.

#1188 PP Counter
  game/assets/texture/wedge.png
  game/database/domains/drop/food.json
  game/database/domains/drop/food2.json
  game/database/resources/texture/wedge.json
  game/domain/definitions/init.lua
  game/view/actorpanel/init.lua
  game/view/actorpanel/lifebar.lua
  game/view/actorpanel/minimap.lua
  game/view/actorpanel/ppbar.lua
  game/view/gameplay/actionhud/buffer.lua
  game/view/gameplay/actionhud/controlhints/init.lua
  game/view/gameplay/actionhud/controlhints/newhand.lua
  game/view/gameplay/actionhud/focusbar.lua
  game/view/gameplay/actionhud/hand/cardinfo.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/ppcounter.lua
  game/view/gameplay/init.lua
  game/view/spritefx/text_rise.lua
  game/view/transmission.lua
Labels: interface

#1190 Removed deprecated instructions on NPC
  game/database/domains/body/npc-adult-1.json
  game/database/domains/body/npc-veteran-2.json
  game/database/domains/sector/initial.json
Labels: refactoring

#1197 Removed Gagdeteer from list + 3 focus
  game/database/settings/playable.json
  game/domain/definitions/action.lua
Labels: gameplay

#1198 Reduce focus bar size to better fit new focus max
  game/view/gameplay/actionhud/focusbar.lua
Labels: interface

#1202 Fixed altar and opening packs view
  game/gamestates/consume_cards.lua
  game/gamestates/open_pack.lua
  game/gamestates/user_turn.lua
  game/view/actorpanel/init.lua
  game/view/consumelist.lua
  game/view/definitions/init.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/minimap.lua
  game/view/packlist.lua
Labels: interface

#1209 Add new stairs for ruins and purple ruins
  game/assets/texture/tiles-purplr.png
  game/assets/texture/tiles.png
Labels: content, graphics

#1207 Actor panel stays longer when gaining exp
  game/gamestates/consume_cards.lua
  game/gamestates/open_pack.lua
  game/gamestates/play.lua
  game/view/actorpanel/init.lua
  game/view/consumelist.lua
Labels: interface, minor

#1208 Actor panel no longers stays locked
  game/gamestates/user_turn.lua
Labels: bug

#1217 Close #1215
  game/database/domains/card/chained-energy.json
Labels: gameplay
