Repository uspgamedev/backdoor, pull requests merged in 2019-04, with the labels that each got.

#1000 Talking NPCs
  game/domain/body.lua
  game/domain/builders/body.lua
  game/domain/builders/sectors.lua
  game/view/dialoguebox.lua
  game/view/sector.lua
Labels: feature, interface

#1008 Correct image to handcursor control hint
  game/view/hand.lua
Labels: bug

#1010 Dialogue images
  game/domain/builders/sectors.lua
  game/view/dialoguebox.lua
Labels: feature

#1016 Fix #1015
  game/domain/body.lua
  game/view/sector.lua
Labels: bug

#1019 Minor code enhancements
  game/domain/body.lua
  game/gamestates/animation.lua
  game/view/sector.lua
Labels: minor, refactoring
