Repository uspgamedev/backdoor, pull requests merged in 2019-12, with the labels that each got.

#1222 New, simpler control map
  game/database/settings/controls.json
  game/view/gameplay/actionhud/init.lua
Labels: UX, refactoring

#1228 Card description on consume list now scrolls if too big
  game/view/consumelist.lua
  game/view/helpers/card.lua
Labels: bug

#1229 Fix #1225
  game/database/domains/card/teleport.json
Labels: bug

#1231 Fix @rilifon's nightmare
  game/view/consumelist.lua
Labels: bug

#1230 Fix healing effects without base power
  game/database/domains/card/calming_down.json
  game/database/domains/card/fix-turret.json
Labels: bug

#1235 Removed 'one-time" condition on old-laddle
  game/database/domains/card/old-laddle.json
Labels: bug

#1233 Show charge counter on widgets
  game/view/card.lua
Labels: interface

#1237 Actor panel now properly stays longer
  game/view/actorpanel/init.lua
Labels: bug

#1244 Describe whether card is temporary or single-use
  game/domain/card.lua
Labels: UX

#1243 Add firebolt icon
  game/assets/texture/fire-bolt.png
  game/database/resources/texture/card-firebolt.json
Labels: graphics

#1250 Add "Flurry of Blows"
  game/assets/texture/flurry-of-blows.png
  game/database/domains/card/flurry-of-blows.json
  game/database/domains/cardset/strikes_expert.json
  game/database/resources/texture/card-flurry-of-blows.json
Labels: content, gameplay

#1249 Fix "firebolt" being able to target self
  game/database/domains/card/firebolt.json
Labels: bug

#1248 Add "Change of Plans" icon
  game/assets/texture/CREDITS.md
  game/assets/texture/change-of-plans.png
  game/assets/texture/triorb.png
  game/database/domains/card/change-of-plans.json
  game/database/resources/texture/card-change-of-plans.json
  game/database/resources/texture/card-divination.json
Labels: content, graphics

#1247 Add arcane burst icon
  game/assets/texture/arcane-burst.png
  game/database/domains/card/arcane-burst.json
  game/database/resources/texture/card-arcane-burst.json
Labels: graphics

#1246 Add missing sectors (type 3)
  game/database/domains/sector/sector03.json
  game/domain/definitions/routemap.lua
Labels: content, gameplay

#1245 Highlight body hit in scanhit preview
  game/database/domains/card/sonic-boom.json
  game/domain/inputs/choose_dir.lua
  game/gamestates/pick_dir.lua
  game/gamestates/user_turn.lua
  game/view/sector.lua
Labels: UX
