Repository uspgamedev/backdoor, pull requests merged in 2019-06, with the labels that each got.

#1030 Add a target for deploying current libs
  .gitignore
  Makefile
Labels: devops

#1031 Updated windows instructions
  README.md
Labels: devops

#1032 Allow devmode anywhere, anytime
  game/database/settings/controls.json
  game/devmode/gui.lua
  game/devmode/view/actor_inspector.lua
  game/devmode/view/actors_menu.lua
  game/devmode/view/bodies_menu.lua
  game/devmode/view/body_inspector.lua
  game/domain/route.lua
  game/gamestates/consume_cards.lua
  game/gamestates/devmode.lua
  game/gamestates/open_pack.lua
  game/gamestates/pick_target.lua
  game/gamestates/pick_widget_slot.lua
  game/gamestates/play.lua
  game/gamestates/ready_ability.lua
  game/gamestates/user_turn.lua
  game/main.lua
Labels: devmode, feature

#1027 Reactive MultiTracks for SoundTrack
  game/assets/bgm/ruins.ogg
  game/assets/bgm/ruins_ac+melody.ogg
  game/assets/bgm/ruins_ac.ogg
  game/assets/bgm/ruins_melody.ogg
  game/database/domains/theme/main-menu.json
  game/database/domains/theme/ruins.json
  game/database/domains/theme/seeds.json
  game/database/domains/theme/zones.json
  game/database/resources/bgm/ruins-danger.json
  game/database/resources/bgm/ruins-default.json
  game/database/schema/theme.lua
  game/domain/route.lua
  game/gamestates/play.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
  game/main.lua
  game/view/soundtrack/init.lua
Labels: feature, juice, music/sound

#1034 SoundTrack fades out in gameover screen
  game/gamestates/gameover.lua
Labels: bug

#1037 Dialogue Boxes have pages + header-only tags
  game/view/dialoguebox.lua
Labels: feature, interface

#1033 Fix/1026
  game/gamestates/settings.lua
Labels: bug

#1039 Dialogue boxes now resize smoothly + Fixed small newpage bug
  game/view/dialoguebox.lua
Labels: bug, juice

#1041 Added simple win screen when player gets a fruit
  game/database/domains/drop/vanth-fruit-concord.json
  game/database/domains/drop/vanth-fruit-culture.json
  game/database/domains/drop/vanth-fruit-discipline.json
  game/domain/effects/win.lua
  game/gamestates/play.lua
  game/gamestates/win.lua
  game/resources/sprite.lua
  game/view/playerwin.lua
Labels: feature

#1045 Fix #1040
  game/devmode/view/bodies_menu.lua
Labels: bug, devmode

#1046 Added animated sprites for dialogue boxes
  game/resources/sprite.lua
  game/view/dialoguebox.lua
Labels: feature

#1050 Improve initial sector
  game/database/domains/body/npc-adult-1.json
  game/database/domains/body/npc-adult-3.json
  game/database/domains/body/npc-elder-1.json
  game/database/domains/body/npc-elder-2.json
  game/database/domains/body/npc-farewell.json
  game/database/domains/body/npc-kid-1.json
  game/database/domains/body/npc-kid-2.json
  game/database/domains/body/npc-veteran-1.json
  game/database/domains/body/npc-welcome.json
  game/database/domains/sector/initial.json
  game/view/consumelist.lua
  game/view/dialoguebox.lua
  game/view/packlist.lua
Labels: juice, refactoring
