Repository uspgamedev/backdoor, pull requests merged in 2020-04, with the labels that each got.

#1264 Add hide vest card
  game/assets/texture/fur-shirt.png
  game/database/domains/actor/brawler.json
  game/database/domains/card/hide-vest.json
  game/database/resources/texture/card-hide-vest.json
Labels: content, gameplay, graphics

#1265 Add disposable defenses card
  game/assets/texture/double-ringed-orb.png
  game/database/domains/card/disposable-defenses.json
  game/database/resources/texture/card-disposable-defenses.json
Labels: content, gameplay, graphics

#1266 Add energy shield card
  game/assets/texture/vibrating-shield.png
  game/database/domains/card/energy-shield.json
  game/database/resources/texture/card-energy-shield.json
Labels: content, gameplay, graphics

#1271 Add plated shield card
  game/database/domains/card/plated-shield.json
  game/database/resources/texture/card-plated-shield.json
Labels: content, gameplay, graphics

#1272 Update push card
  game/assets/texture/glowing-hands.png
  game/database/domains/card/push.json
  game/database/resources/texture/card-push.json
  game/domain/operators/hitscan.lua
  game/domain/operators/pos_difference.lua
Labels: content, gameplay, graphics

#1273 Remaining Slime Cards
  game/assets/texture/sonic-boom.png
  game/database/domains/card/sonic-boom.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/sticky_flame.json
  game/database/resources/texture/card-sonic-boom.json
  game/view/gameplay/actionhud/hand/cardinfo.lua
Labels: content

#1274 Update illusion of darkness card
  game/database/domains/card/blind.json
  game/database/domains/card/illusion_of_darkness.json
Labels: content, gameplay

#1275 Add entangle card
  game/assets/texture/curling-vines.png
  game/database/domains/card/entangle.json
  game/database/domains/card/entangled.json
  game/database/resources/texture/card-entangle.json
Labels: content, gameplay, graphics

#1278 Update stomp card
  game/database/domains/card/stomp.json
  game/domain/effects/place_widget_on_area.lua
Labels: content, gameplay

#1277 Added dash card
  game/assets/sfx/dash.wav
  game/assets/texture/dash.png
  game/database/domains/card/dash.json
  game/database/resources/sfx/dash.json
  game/database/resources/texture/card-dash.json
Labels: content, gameplay, graphics

#1280 Add chained surge card
  game/assets/texture/defibrilate.png
  game/database/domains/card/chained-surge.json
  game/database/resources/texture/card-chained-surge.json
Labels: content, gameplay, graphics

#1281 Fixed and rebalanced rush
  game/database/domains/card/rush.json
Labels: content, gameplay

#1282 Rebalanced teleport card
  game/database/domains/card/teleport.json
Labels: content, gameplay

#1283 Update jump card
  game/database/domains/card/jump.json
Labels: content, gameplay

#1288 Using a global variable to differentiate dev and release vers.
  game/gamestates/play.lua
  game/main.lua
Labels: devmode, devops

#1289 Read development flag from command line
  Makefile
  game/gamestates/play.lua
  game/main.lua
Labels: devops

#1293 Deploy for 0.3
  .gitignore
  Makefile
Labels: devops

#1298 Remove duplicate miracle card
  game/database/domains/actor/brawler.json
  game/database/domains/card/miracle.json
  game/database/domains/card/signet-of-inspiration.json
Labels: bug, content

#1297 Update README for löve 11.3
  README.md
Labels: devops

#1299 Fixed NPCs dialogue to use current control scheme
  game/database/domains/body/npc-adult-2.json
  game/database/domains/body/npc-elder-1.json
  game/database/domains/body/npc-elder-2.json
  game/database/domains/body/npc-farewell.json
Labels: bug

#1302 Ignore imgui library inside game folder
  game/.gitignore
Labels: devops

#1305 Fix later monsters not dropping right packs
  game/database/domains/body/corgi.json
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/drop/doggo-pack.json
  game/database/domains/drop/eye-pack.json
  game/database/domains/drop/imp-pack.json
Labels: bug, content

#1303 Allow PAUSE (escape) to exit setting menu
  game/gamestates/settings.lua
Labels: UX

#1304 Actually disable key binding menu from production
  game/gamestates/start_menu.lua
  game/view/actor.lua
Labels: bug

#1306 Proposal: continuous hand
  game/assets/texture/lightning-electron.png
  game/database/domains/actor/dumb.json
  game/database/domains/actor/fiendish.json
  game/database/domains/actor/grinful.json
  game/database/domains/actor/newbieslayer.json
  game/database/domains/card/chained-energy.json
  game/database/domains/card/concentration.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/resources/texture/card-chained-energy.json
  game/domain/actor.lua
  game/domain/definitions/action.lua
  game/domain/maneuver/discard_card.lua
  game/domain/maneuver/interact.lua
  game/domain/maneuver/play_card.lua
  game/domain/route.lua
  game/domain/sector.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/view/gameplay/actionhud/buffer.lua
  game/view/gameplay/actionhud/hand/init.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/minimap.lua
  game/view/gameplay/init.lua
Labels: feature, gameplay

#1310 Fixed not drawing initial hand when loading save
  game/view/gameplay/actionhud/hand/init.lua
Labels: bug

#1311 Fixed typo
  game/database/domains/body/hearthborn.json
Labels: bug

#1312 Cards cost focus and focus regenerates per tick
  game/domain/actor.lua
  game/domain/definitions/action.lua
  game/domain/maneuver/end_focus.lua
  game/domain/maneuver/interact.lua
  game/domain/maneuver/play_card.lua
  game/gamestates/user_turn.lua
  game/view/gameplay/actionhud/focusbar.lua
Labels: feature, gameplay

#1315 Change focus regen to 1/turn
  game/domain/actor.lua
  game/domain/definitions/action.lua
Labels: gameplay

#1319 Cards can cause either full or half exhaustion
  game/database/domains/card/arcane-burst.json
  game/database/schema/card.lua
  game/domain/card.lua
  game/domain/definitions/action.lua
  game/domain/effects/spend_pp.lua
  game/domain/maneuver/discard_card.lua
  game/domain/maneuver/draw_new_hand.lua
  game/domain/maneuver/idle.lua
  game/domain/maneuver/interact.lua
  game/domain/maneuver/move.lua
  game/domain/maneuver/play_card.lua
  game/gamestates/user_turn.lua
Labels: feature, gameplay

#1317 Attempt to balance altar spawn
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector03.json
Labels: gameplay

#1320 Drop less food since they provide more cards now
  game/database/domains/body/corgi.json
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
Labels: content, gameplay

#1321 Improved handview
  game/view/gameplay/actionhud/focusbar.lua
  game/view/gameplay/actionhud/hand/init.lua
  game/view/gameplay/actionhud/init.lua
Labels: interface

#1323 Preview turn order
  game/domain/sector.lua
  game/gamestates/play.lua
  game/gamestates/user_turn.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/turnpreview.lua
Labels: UX, interface

#1332 Fix #1331, fix #1330, fix #1329
  game/domain/sector.lua
  game/gamestates/user_turn.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/turnpreview.lua
Labels: bug

#1328 Use curl to get current LÖVE from bitbucket
  Makefile
Labels: devops

#1336 Preview turns only up to next player's turn
  game/view/gameplay/actionhud/turnpreview.lua
Labels: UX

#1337 Preview half exhaustion too
  game/database/domains/card/concentration.json
  game/domain/card.lua
  game/domain/sector.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/turnpreview.lua
Labels: UX

#1338 Fix #1309
  game/view/gameplay/actionhud/init.lua
Labels: bug

#1339 Using icons for turn preview
  game/assets/texture/demobody_turn_icon.png
  game/assets/texture/floating_eye_turn_icon.png
  game/assets/texture/goodboy_turn_icon.png
  game/assets/texture/hearthborn_turn_icon.png
  game/assets/texture/hillborn_turn_icon.png
  game/assets/texture/imp_turn_icon.png
  game/assets/texture/slime_turn_icon.png
  game/assets/texture/stove_turn_icon.png
  game/database/domains/appearance/corgi.json
  game/database/domains/appearance/demobody.json
  game/database/domains/appearance/eyedemon.json
  game/database/domains/appearance/hearthborn.json
  game/database/domains/appearance/hillborn.json
  game/database/domains/appearance/imp.json
  game/database/domains/appearance/slime.json
  game/database/domains/appearance/stove.json
  game/database/resources/texture/turn-icon-corgi.json
  game/database/resources/texture/turn-icon-demobody.json
  game/database/resources/texture/turn-icon-eyedemon.json
  game/database/resources/texture/turn-icon-hearthborn.json
  game/database/resources/texture/turn-icon-hillborn.json
  game/database/resources/texture/turn-icon-imp.json
  game/database/resources/texture/turn-icon-slime.json
  game/database/resources/texture/turn-icon-stove.json
  game/database/schema/appearance.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/actionhud/turnpreview.lua
Labels: interface

#1340 Stop wasting frames on non-animations
  game/domain/actor.lua
  game/gamestates/animation.lua
  game/gamestates/play.lua
  game/infra/switcher.lua
  game/main.lua
  game/view/sector.lua
Labels: bug

#1343 Fix Rush and Chained Energy descriptions
  game/database/domains/card/sidestep.json
  game/domain/effects/damage_on_area.lua
  game/domain/inputs/choose_dir.lua
  game/domain/inputs/pos.lua
  game/domain/operators/find_nearest_body.lua
  game/domain/operators/hitscan.lua
  game/domain/operators/translated.lua
Labels: bug

#1345 Fix #1344
  game/gamestates/user_turn.lua
  game/view/sector.lua
Labels: bug

#1346 FoV performance improvements
  .gitignore
  game/common/profiler.lua
  game/common/visibility.lua
  game/domain/sector.lua
  game/main.lua
  game/view/sector/bodyview.lua
Labels: refactoring
