Repository uspgamedev/backdoor, pull requests merged in 2020-10, with the labels that each got.

#1552 Fix camera tween
  game/common/camera.lua
Labels: bug, juice

#1553 Fix card tween to avoid shaking
  game/view/gameplay/actionhud/hand/init.lua
Labels: bug, juice

#1555 Added control hints + fadein to settings screen
  game/view/settings.lua
Labels: UX, interface

#1557 Added control hints to packlist
  game/view/packlist.lua
Labels: UX, interface

#1564 Fix #1561
  game/view/gameplay/actionhud/hand/cardinfo.lua
  game/view/gameplay/actionhud/infopanel/init.lua
Labels: bug, interface, juice

#1566 Open packs in bulk
  game/domain/actor.lua
  game/gamestates/open_pack.lua
  game/gamestates/user_turn.lua
  game/view/packlist.lua
Labels: UX, feature

#1568 Generating packs with weighted distribution
  game/database/schema/collection.lua
  game/domain/pack.lua
Labels: feature, gameplay
