Repository uspgamedev/backdoor, pull requests merged in 2020-07, with the labels that each got.

#1426 Update IMGUI and use new font for devmode
  game/assets/font/Anton-OFL.txt
  game/assets/font/PTMono-Regular-OFL.txt
  game/assets/font/PTMono-Regular.ttf
  game/devmode/gui.lua
  game/devmode/view/specification_editor.lua
Labels: devmode, devops

#1428 Disable profiler in production
  game/common/profiler.lua
Labels: bug, devops

#1430 Remove signature abilities from the code
  game/database/domains/action/bolting.json
  game/database/domains/action/bullet.json
  game/database/domains/action/glare.json
  game/database/domains/action/punch.json
  game/database/domains/action/scratch.json
  game/database/domains/action/tackle.json
  game/database/domains/actor/brawler.json
  game/database/domains/actor/dumb-slime.json
  game/database/domains/actor/dumb-stove.json
  game/database/domains/actor/dumb.json
  game/database/domains/actor/fiendish-eye.json
  game/database/domains/actor/fiendish.json
  game/database/domains/actor/grinful-imp.json
  game/database/domains/actor/grinful.json
  game/database/domains/actor/newbieslayer.json
  game/database/domains/actor/sage.json
  game/database/domains/actor/sentient.json
  game/database/domains/actor/strong.json
  game/database/domains/actor/tutorial-brawler.json
  game/database/domains/actor/tutorial-idle.json
  game/database/schema/action.lua
  game/database/schema/actor.lua
  game/devmode/gui.lua
  game/devmode/view/input/ability.lua
  game/domain/actor.lua
  game/domain/definitions/action.lua
  game/domain/maneuver/use_signature.lua
Labels: refactoring

#1436 Fix domain menu crash
  game/devmode/gui.lua
Labels: bug, devmode

#1438 New, simpler HP formula
  game/database/domains/body/corgi.json
  game/database/domains/body/demihuman.json
  game/database/domains/body/eye.json
  game/database/domains/body/hearthborn.json
  game/database/domains/body/imp.json
  game/database/domains/body/machine.json
  game/database/domains/body/npc-base.json
  game/database/domains/body/obstacle.json
  game/database/domains/body/rewasvat.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
  game/database/domains/body/tutorial-slime.json
  game/database/schema/body.lua
  game/devmode/gui.lua
  game/devmode/view/actor_inspector.lua
  game/devmode/view/body_inspector.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/definitions/aptitude.lua
  game/domain/definitions/attribute.lua
  game/domain/definitions/init.lua
  game/domain/operators/get_attribute.lua
  game/domain/operators/get_body_attribute.lua
Labels: feature, gameplay

#1440 Remove obsolete Body:getConsumption()
  game/domain/body.lua
  game/view/gameplay/actionhud/buffer.lua
  game/view/helpers/newhand_card.lua
Labels: refactoring

#1439 Added better indication for quick cards (spend half exhaustion)
  game/assets/texture/quick_icon.png
  game/database/resources/texture/quick-card-icon.json
  game/domain/card.lua
  game/domain/definitions/colors.lua
  game/view/card.lua
  game/view/gameplay/actionhud/hand/cardinfo.lua
Labels: UX, interface

#1441 Use more direct computation for monsters' upgrades
  game/database/domains/body/npc-welcome.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/domain/builders/sector.lua
  game/domain/transformers/encounters.lua
Labels: feature, gameplay

#1442 Remove obsolete actor collection
  game/database/domains/actor/brawler.json
  game/database/domains/actor/dumb-slime.json
  game/database/domains/actor/dumb-stove.json
  game/database/domains/actor/dumb.json
  game/database/domains/actor/fiendish-eye.json
  game/database/domains/actor/fiendish.json
  game/database/domains/actor/gadgeteer.json
  game/database/domains/actor/grinful-imp.json
  game/database/domains/actor/grinful.json
  game/database/domains/actor/newbieslayer.json
  game/database/domains/actor/sage.json
  game/database/domains/actor/sentient.json
  game/database/domains/actor/strong.json
  game/database/domains/actor/tutorial-idle.json
  game/database/schema/actor.lua
Labels: refactoring

#1443 Close #1425 and fix #1423
  game/database/domains/drop/doggo-pack.json
  game/database/domains/drop/eye-pack.json
  game/database/domains/drop/food.json
  game/database/domains/drop/food2.json
  game/database/domains/drop/heart.json
  game/database/domains/drop/imp-pack.json
  game/database/domains/drop/pack.json
  game/database/domains/drop/slime-pack.json
  game/database/domains/drop/stove-pack.json
  game/database/domains/drop/vanth-fruit-concord.json
  game/database/domains/drop/vanth-fruit-culture.json
  game/database/domains/drop/vanth-fruit-discipline.json
  game/database/schema/drop.lua
  game/domain/actor.lua
  game/view/sector.lua
Labels: bug, devmode, feature

#1446 Allow hitscan operator to pass bodies
  game/database/domains/card/dash.json
  game/database/domains/card/greater-rush.json
  game/database/domains/card/rush.json
  game/domain/operators/hitscan.lua
Labels: content, feature, gameplay

#1444 Allow ESC to exit from a number of states
  game/gamestates/character_build.lua
  game/gamestates/start_menu.lua
  game/view/gameplay/actionhud/init.lua
Labels: UX

#1445 Widen ability preview box
  game/devmode/view/input/ability.lua
Labels: UX, devmode

#1447 Outlining actors turn
  game/resources/sprite.lua
  game/view/helpers/outline.lua
  game/view/sector.lua
  game/view/sector/bodyview.lua
Labels: UX

#1451 UI color review
  game/domain/definitions/colors.lua
  game/view/gameplay/actionhud/buffer.lua
  game/view/gameplay/actionhud/ppcounter.lua
Labels: graphics

#1456 Fix lower save button not working
  game/database/domains/actor/brawler.json
  game/database/domains/card/arcane-burst.json
  game/devmode/view/specification_editor.lua
Labels: bug, devmode

#1457 Make control hints context-aware
  game/database/resources/texture/button-key-action-down.json
  game/database/resources/texture/button-key-action-left.json
  game/database/resources/texture/button-key-action-right.json
  game/database/resources/texture/button-key-action-up.json
  game/database/resources/texture/button-key-shoulder-left.json
  game/database/resources/texture/button-key-shoulder-right.json
  game/view/gameplay/actionhud/buffer.lua
  game/view/gameplay/actionhud/controlhint.lua
  game/view/gameplay/actionhud/controlhints/cancel.lua
  game/view/gameplay/actionhud/controlhints/confirm.lua
  game/view/gameplay/actionhud/controlhints/init.lua
  game/view/gameplay/actionhud/controlhints/newhand.lua
  game/view/gameplay/actionhud/controlhints/openpacks.lua
  game/view/gameplay/actionhud/controlhints/showstats.lua
  game/view/gameplay/actionhud/controlhints/togglehints.lua
  game/view/gameplay/actionhud/hand/cardinfo.lua
  game/view/gameplay/actionhud/init.lua
Labels: UX, refactoring
