Repository uspgamedev/backdoor, pull requests merged in 2020-05, with the labels that each got.

#1348 Content: tutorial map
  game/database/domains/body/obstacle.json
  game/database/domains/body/tutorial-slime.json
  game/database/domains/sector/initial.json
  game/database/domains/sector/tutorial.json
  game/domain/builders/route.lua
  game/domain/builders/sectors.lua
  game/domain/definitions/routemap.lua
  game/domain/sector.lua
  game/domain/transformers/bootstrap.lua
  game/gamestates/play.lua
Labels: content

#1349 New initial map: the outpost
  game/database/domains/sector/outpost.json
  game/domain/definitions/routemap.lua
Labels: content

#1350 Fix stunning blow card targeting oneself
  game/database/domains/card/stunning-blow.json
Labels: bug, content

#1357 Trigger missing open pack tutorial
  game/gamestates/animation.lua
Labels: bug, content

#1356 Extend stun duration
  game/database/domains/card/stunned.json
Labels: content, gameplay

#1355 Fix tutorial hint about which button uses cards
  game/gamestates/tutorial_hint.lua
Labels: bug, content

#1358 Add tactical hints to cards
  game/database/domains/card/firebolt.json
  game/database/schema/card.lua
  game/domain/inputs/choose_dir.lua
  game/domain/inputs/choose_target.lua
Labels: feature

#1360 Added dumb slime and dumb stove decks
  game/database/domains/actor/dumb-slime.json
  game/database/domains/actor/dumb-stove.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
Labels: feature, refactoring

#1362 Monsters now use cards with targets
  game/domain/behaviors/aggro.lua
  game/domain/behaviors/helpers/listcardplays.lua
Labels: feature, gameplay

#1363 Randomize card plays
  game/domain/behaviors/aggro.lua
  game/domain/behaviors/helpers/listcardplays.lua
Labels: feature, gameplay

#1364 Monsters choose dir too
  game/domain/behaviors/helpers/listcardplays.lua
Labels: feature, gameplay

#1365 Added first version of enemy decks
  game/database/domains/actor/dumb-stove.json
  game/database/domains/actor/fiendish-eye.json
  game/database/domains/actor/grinful-imp.json
  game/database/domains/actor/newbieslayer.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
Labels: feature

#1366 Add heart drop that heals life
  game/assets/texture/heart-drop.png
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/body/rewasvat.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
  game/database/domains/drop/heart.json
  game/database/resources/sprite/heart.json
  game/database/resources/texture/drop-heart.json
  game/domain/actor.lua
  game/domain/inputs/hp_not_full.lua
Labels: content, gameplay

#1370 Add card "Bloodthirst"
  game/assets/texture/bleeding-eye.png
  game/database/domains/actor/brawler.json
  game/database/domains/card/bloodthirst.json
  game/database/resources/texture/card-bloodthirst.json
  game/domain/definitions/triggers.lua
  game/domain/sector.lua
Labels: content, gameplay

#1372 Reduce heart drops
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/body/rewasvat.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
Labels: content, gameplay

#1373 Announce cards monsters use
  game/gamestates/animations/play_art_card.lua
  game/gamestates/animations/play_widget_card.lua
Labels: UX

#1374 Added control hint for idle
  game/view/gameplay/actionhud/controlhints/cancel.lua
  game/view/gameplay/actionhud/init.lua
Labels: interface

#1376 Fix drop animations not happening
  game/domain/sector.lua
  game/gamestates/play.lua
  game/view/spritefx/drop_spread.lua
Labels: bug

#1378 Properly updating docks in startup
  game/view/gameplay/actionhud/init.lua
Labels: bug
