Repository uspgamedev/backdoor, pull requests merged in 2020-08, with the labels that each got.

#1465 Add LuaFormatter configuration file
  .gitignore
  .lua-format
  game/draw.lua
Labels: devops

#1470 Added new faction type: Inert
  game/database/domains/body/corgi.json
  game/database/domains/body/eye.json
  game/database/domains/body/imp.json
  game/database/domains/body/obstacle.json
  game/database/domains/body/rewasvat.json
  game/database/domains/body/slime.json
  game/database/domains/body/stove.json
  game/database/domains/body/tutorial-slime.json
  game/database/domains/faction/aggressive.json
  game/database/domains/faction/agressive.json
  game/database/domains/faction/inert.json
  game/domain/actor.lua
Labels: feature

#1472 Add crate prop and use it on tutorial map
  game/assets/texture/crate.png
  game/database/domains/appearance/prop-crate.json
  game/database/domains/body/crate.json
  game/database/domains/sector/tutorial.json
  game/database/resources/sprite/prop-crate.json
  game/database/resources/texture/prop-crate.json
Labels: content, graphics

#1473 Generate props
  game/database/domains/body/crate.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/database/schema/sector.lua
  game/domain/behaviors/helpers/findtarget.lua
  game/domain/transformers/props.lua
Labels: content, feature, gameplay

#1474 Show first contact tutorial on aggressives and inerts
  game/domain/actor.lua
  game/gamestates/user_turn.lua
Labels: bug

#1475 Properly destroy control hint for "A"
  game/view/gameplay/actionhud/init.lua
Labels: bug

#1476 Turn preview stops checking for props
  game/view/gameplay/actionhud/turnpreview.lua
Labels: bug

#1483 Remove obsolete trigger usage
  game/domain/maneuver/play_card.lua
Labels: refactoring

#1481 Add scripted operator
  game/devmode/view/input/reference.lua
  game/domain/operators/script.lua
Labels: devmode, feature

#1482 Preview static abilities in other abilities
  game/common/formula.lua
  game/database/domains/card/bloodthirst.json
  game/database/schema/card.lua
  game/devmode/view/input/ability.lua
  game/domain/ability.lua
  game/domain/inputs/register.lua
  game/domain/operators/effective_power.lua
Labels: UX, devmode, feature, gameplay

#1484 Add rock prop
  game/assets/texture/rock.png
  game/database/domains/appearance/prop-rock.json
  game/database/domains/body/rock.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/database/resources/sprite/prop-rock.json
  game/database/resources/texture/prop-rock.json
Labels: content, gameplay

#1487 Add Create Rock card
  game/assets/texture/card-rock.png
  game/database/domains/card/create-rock.json
  game/database/resources/texture/card-create-rock.json
  game/domain/effects/make_body.lua
Labels: content, gameplay

#1488 Refactores sfx pitch variation to use database
  game/database/resources/sfx/attack-hit.json
  game/database/resources/sfx/back-menu.json
  game/database/resources/sfx/denied.json
  game/database/resources/sfx/focus-gain.json
  game/database/resources/sfx/focus-used.json
  game/database/resources/sfx/footstep.json
  game/database/resources/sfx/get-item.json
  game/database/resources/sfx/holdbar-confirm.json
  game/database/resources/sfx/ok-menu.json
  game/database/resources/sfx/select-card.json
  game/database/resources/sfx/select-menu.json
  game/database/resources/sfx/toggle-card.json
  game/database/schema/sfx.lua
  game/gamestates/animations/body_moved.lua
  game/gamestates/animations/take_damage.lua
  game/gamestates/character_build.lua
  game/gamestates/consume_cards.lua
  game/gamestates/open_pack.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
  game/gamestates/user_turn.lua
  game/helpers/playsfx.lua
  game/resources/init.lua
  game/view/actor/attr.lua
  game/view/actorpanel/stats/attribute.lua
  game/view/gameplay/actionhud/focusbar.lua
  game/view/gameplay/actionhud/hand/init.lua
  game/view/helpers/holdbar.lua
Labels: refactoring

#1490 Only show life and energy bars when focused
  game/domain/body.lua
  game/helpers/playsfx.lua
  game/view/gameplay/actionhud/init.lua
  game/view/gameplay/init.lua
  game/view/sector.lua
  game/view/sector/energybar.lua
  game/view/sector/lifebarbatch.lua
Labels: UX, feature

#1494 Hopefully fix endless announcement thing
  game/view/helpers/tweenvalue.lua
Labels: UX, bug

#1492 Balance Bloodthirst considering props
  game/database/domains/card/bloodthirst.json
  game/domain/inputs/is_in_faction.lua
  game/domain/operators/count_nearby_bodies.lua
  game/domain/sector.lua
Labels: content, gameplay

#1491 Fix text rise not showing up
  game/gamestates/animations/text_rise.lua
  game/view/spritefx/text_rise.lua
Labels: UX, bug

#1495 Fix bad speed stat being used
  game/domain/actor.lua
  game/domain/definitions/aptitude.lua
Labels: bug, gameplay

#1506 Give projectiles a curved trajectory
  game/gamestates/animations/projectile.lua
Labels: juice

#1516 Increase base focus regen
  game/domain/definitions/aptitude.lua
Labels: feature, gameplay

#1515 Reduce Side Step cost
  game/database/domains/card/sidestep.json
Labels: content, gameplay

#1514 Change Concentration to buff targeted damage
  game/database/domains/card/concentration.json
Labels: content, gameplay

#1513 Distribute XP based on deck composition
  game/domain/actor.lua
  game/gamestates/tutorial_hint.lua
  game/view/consumelist.lua
Labels: feature, gameplay
