Repository uspgamedev/backdoor, pull requests merged in 2020-11, with the labels that each got.

#1570 Fix first-time focus being dummy text
  game/view/gameplay/actionhud/hand/init.lua
Labels: bug

#1569 Fix crash when you exit with ESC
  game/view/gameplay/actionhud/bodyinspector/init.lua
Labels: bug

#1578 Fullscreen support
  game/conf.lua
  game/database/settings/controls.json
  game/database/settings/user-preferences.json
  game/gamestates/settings.lua
  game/main.lua
  game/view/settings.lua
Labels: feature

#1581 Fixed jump + greater jump
  game/database/domains/card/greater-jump.json
  game/database/domains/card/jump.json
Labels: bug

#1579 Cave generation
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/schema/sector.lua
  game/domain/definitions/schematics.lua
  game/domain/transformers/automata.lua
  game/domain/transformers/bootstrap.lua
  game/domain/transformers/connections.lua
  game/domain/transformers/exits.lua
  game/domain/transformers/fillings.lua
  game/domain/transformers/helpers/sectorgrid.lua
  game/domain/transformers/random_fill.lua
  game/domain/transformers/remove_disconnected.lua
Labels: feature, gameplay

#1586 Fill ruin margins with walls
  game/database/domains/sector/sector01.json
  game/domain/transformers/rooms.lua
Labels: content, gameplay

#1587 Fix ai state not loading
  game/domain/behaviors/init.lua
Labels: bug, gameplay

#1593 Fix sonic boom not stopping on bodies
  game/database/domains/card/sonic-boom.json
Labels: bug, content, gameplay

#1594 Change fullscreen mode
  game/conf.lua
  game/database/settings/user-preferences.json
Labels: bug, graphics

#1597 Fix makefile cp command
  Makefile
Labels: devops

#1599 Reduce time after "text rising" effect
  game/view/sector/risingtext.lua
Labels: UX
