Repository uspgamedev/backdoor, pull requests merged in 2020-06, with the labels that each got.

#1379 Focus camera on acting actor
  game/gamestates/animations/play_art_card.lua
  game/gamestates/animations/play_widget_card.lua
  game/view/sector.lua
Labels: UX

#1380 New animation for taking damage
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/gamestates/animations/take_damage.lua
  game/view/sector/bodyview.lua
  game/view/sector/risingtext.lua
  game/view/spritefx/body_moved.lua
Labels: UX, juice

#1381 New body act animation with correct timing
  game/domain/maneuver/play_card.lua
  game/gamestates/animations/play_art_card.lua
  game/gamestates/animations/play_widget_card.lua
  game/view/sector/bodyview.lua
  game/view/spritefx/body_acted.lua
Labels: UX, juice

#1383 Reduce enemy animation
  game/gamestates/animations/play_art_card.lua
  game/gamestates/animations/play_widget_card.lua
Labels: UX

#1384 Add ability preview in devmode editors
  game/devmode/view/input/ability.lua
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/heal.lua
  game/domain/operators/get_attribute.lua
  game/domain/operators/get_body_attribute.lua
  game/domain/operators/integer_binop.lua
Labels: devmode

#1385 Add frame-by-frame animation effect
  game/assets/texture/.gitignore
  game/assets/texture/fx-bonk.png
  game/database/resources/sprite/fx-bonk.json
  game/database/resources/texture/fx-bonk.json
  game/gamestates/animations/take_damage.lua
  game/resources/sprite.lua
  game/view/helpers/animationfx.lua
Labels: juice

#1386 Restore step sfx when moving
  game/gamestates/animations/body_moved.lua
Labels: bug, music/sound

#1387 Use 'attack-hit' sfx for all damaging cards
  game/assets/texture/fx-bonk.ase
  game/database/domains/card/arcane-burst.json
  game/database/domains/card/auto-fire.json
  game/database/domains/card/bone-club-crush.json
  game/database/domains/card/energy-beam.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/flurry-of-blows.json
  game/database/domains/card/greater-jump.json
  game/database/domains/card/greater-rush.json
  game/database/domains/card/plasma-bomb.json
  game/database/domains/card/proximity-detector.json
  game/database/domains/card/reckless-smash.json
  game/database/domains/card/roundhouse-kick.json
  game/database/domains/card/rush.json
  game/database/domains/card/rusty-blaster-shot.json
  game/database/domains/card/self-destruct.json
  game/database/domains/card/sonic-boom.json
  game/database/domains/card/spark-rod-aoe.json
  game/database/domains/card/spark-rod-target.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stomp.json
  game/domain/effects/damage_on_area.lua
Labels: music/sound

#1389 Preview both formula and value of damage/heal
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/heal.lua
Labels: UX

#1390 Added pitch variation to games sfxs
  game/gamestates/animations/body_moved.lua
  game/gamestates/animations/take_damage.lua
  game/gamestates/character_build.lua
  game/gamestates/consume_cards.lua
  game/gamestates/open_pack.lua
  game/gamestates/pick_dir.lua
  game/gamestates/pick_target.lua
  game/gamestates/pick_widget_slot.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
  game/gamestates/user_turn.lua
  game/view/actor/attr.lua
  game/view/actorpanel/stats/attribute.lua
  game/view/helpers/holdbar.lua
  game/view/sector.lua
Labels: music/sound

#1391 Fix jump animation
  game/database/domains/card/greater-jump.json
  game/database/domains/card/jump.json
  game/gamestates/animations/body_jumped.lua
  game/view/sector/bodyview.lua
  game/view/spritefx/body_jumped.lua
Labels: bug, juice

#1393 Tested particles effect + healing effect improved
  game/domain/effects/heal.lua
  game/gamestates/animations/heal.lua
  game/view/helpers/particles.lua
Labels: UX, feature

#1394 Add projectile animation
  game/assets/texture/projectile-energy-sphere.png
  game/database/domains/card/chained-energy.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/impact-grenade.json
  game/database/domains/card/plasma-bomb.json
  game/database/domains/card/rusty-blaster-shot.json
  game/database/resources/sprite/projectile-energy-sphere.json
  game/database/resources/texture/projectile-energy-sphere.json
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/gamestates/animations/projectile.lua
  game/view/sector/bodyview.lua
Labels: juice

#1395 Improve description of Chained Energy
  game/database/domains/card/chained-energy.json
  game/domain/inputs/pos.lua
Labels: UX

#1396 Improve trigger descriptions
  game/domain/ability.lua
  game/domain/card.lua
  game/domain/definitions/triggers.lua
  game/domain/effects/consume_cards.lua
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/destroy_body.lua
  game/domain/effects/draw_card.lua
  game/domain/effects/gain_focus.lua
  game/domain/effects/give_pack.lua
  game/domain/effects/heal.lua
  game/domain/effects/lose_life.lua
  game/domain/effects/make_body.lua
  game/domain/effects/move_to.lua
  game/domain/effects/place_widget.lua
  game/domain/effects/place_widget_on_area.lua
  game/domain/effects/reward_pp.lua
  game/gamestates/pick_widget_slot.lua
  game/view/pickwidget.lua
Labels: UX

#1401 Use tree editor for ability commands.
  game/devmode/view/input/ability.lua
  game/devmode/view/specification_editor.lua
Labels: devmode

#1400 Refactor power formula into separate operator
  game/database/domains/card/arcane-burst.json
  game/database/domains/card/auto-fire.json
  game/database/domains/card/bone-club-crush.json
  game/database/domains/card/chained-energy.json
  game/database/domains/card/energy-beam.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/flurry-of-blows.json
  game/database/domains/card/greater-jump.json
  game/database/domains/card/greater-rush.json
  game/database/domains/card/greater_healing_potion.json
  game/database/domains/card/heal.json
  game/database/domains/card/healing_potion.json
  game/database/domains/card/hook-n-uppercut.json
  game/database/domains/card/impact-grenade.json
  game/database/domains/card/jump.json
  game/database/domains/card/lead-pipe-strike.json
  game/database/domains/card/old-laddle-strike.json
  game/database/domains/card/plasma-bomb.json
  game/database/domains/card/proximity-detector.json
  game/database/domains/card/reckless-smash.json
  game/database/domains/card/roundhouse-kick.json
  game/database/domains/card/rush.json
  game/database/domains/card/rusty-blaster-shot.json
  game/database/domains/card/self-destruct.json
  game/database/domains/card/sonic-boom.json
  game/database/domains/card/spark-rod-aoe.json
  game/database/domains/card/spark-rod-target.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/strike.json
  game/database/domains/card/trained-strike.json
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/heal.lua
  game/domain/operators/effective_power.lua
Labels: bug, refactoring

#1397 Static abilities
  game/database/domains/card/arcane-burst.json
  game/database/domains/card/auto-fire.json
  game/database/domains/card/bloodthirst.json
  game/database/domains/card/bone-club-crush.json
  game/database/domains/card/chained-energy.json
  game/database/domains/card/energy-beam.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/flurry-of-blows.json
  game/database/domains/card/greater-jump.json
  game/database/domains/card/greater-rush.json
  game/database/domains/card/heal.json
  game/database/domains/card/hook-n-uppercut.json
  game/database/domains/card/jump.json
  game/database/domains/card/lead-pipe-strike.json
  game/database/domains/card/old-laddle-strike.json
  game/database/domains/card/proximity-detector.json
  game/database/domains/card/reckless-smash.json
  game/database/domains/card/roundhouse-kick.json
  game/database/domains/card/rush.json
  game/database/domains/card/rusty-blaster-shot.json
  game/database/domains/card/self-destruct.json
  game/database/domains/card/sonic-boom.json
  game/database/domains/card/spark-rod-aoe.json
  game/database/domains/card/spark-rod-target.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/strike.json
  game/database/domains/card/trained-strike.json
  game/database/schema/card.lua
  game/devmode/view/input/ability.lua
  game/devmode/view/input/reference.lua
  game/domain/ability.lua
  game/domain/card.lua
  game/domain/effects/damage_on_area.lua
  game/domain/effects/damage_on_target.lua
  game/domain/effects/heal.lua
  game/domain/inputs/enum.lua
  game/domain/inputs/integer.lua
  game/domain/inputs/is_same_enum.lua
  game/domain/inputs/is_same_integer.lua
Labels: feature, gameplay

#1402 Fix tree node collapsing when you change output
  game/devmode/view/input/ability.lua
Labels: bug, devmode

#1403 Fix heart drop crash
  game/database/domains/drop/heart.json
Labels: bug

#1404 Use attribute-dependent focus regen
  game/devmode/view/actor_inspector.lua
  game/devmode/view/body_inspector.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/definitions/aptitude.lua
  game/domain/definitions/attribute.lua
Labels: feature, gameplay

#1409 Fix some cards using obsolete field "amount"
  game/database/domains/card/greater_healing_potion.json
  game/database/domains/card/healing_potion.json
  game/database/domains/card/impact-grenade.json
  game/database/domains/card/plasma-bomb.json
Labels: bug

#1406 Increase Max HP with power level
  game/database/domains/body/obstacle.json
  game/devmode/view/actor_inspector.lua
  game/devmode/view/body_inspector.lua
  game/domain/actor.lua
  game/domain/body.lua
  game/domain/definitions/aptitude.lua
Labels: feature, gameplay

#1415 Tweaked pitch variation on changing menu options
  game/gamestates/character_build.lua
  game/gamestates/settings.lua
  game/gamestates/start_menu.lua
Labels: music/sound

#1419 New tile set for first part
  game/assets/texture/tiles.png
  game/database/resources/tileset/demo.json
  game/database/resources/tileset/otherdemo.json
  game/database/resources/tileset/ruins.json
  game/database/schema/tileset.lua
  game/domain/definitions/colors.lua
  game/resources/tileset.lua
  game/view/sector/mesh/wall.lua
  game/view/sector/tilemap.lua
  game/view/sector/wall.lua
  game/view/startmenu.lua
Labels: graphics

#1421 Fix #1408
  game/domain/effects/place_widget.lua
  game/domain/effects/place_widget_on_area.lua
  game/gamestates/animations/place_widget_card.lua
Labels: UX, bug

#1418 SFXS for hand UI and related elements
  game/assets/sfx/close_hand.wav
  game/assets/sfx/cond_off.wav
  game/assets/sfx/cond_on.wav
  game/assets/sfx/create_card.wav
  game/assets/sfx/discard-temporary-card.wav
  game/assets/sfx/draw_card.wav
  game/assets/sfx/equip_off.wav
  game/assets/sfx/equip_on.wav
  game/assets/sfx/gain_focus.wav
  game/assets/sfx/open_hand.wav
  game/assets/sfx/select_card.wav
  game/assets/sfx/shuffle_hand.wav
  game/assets/sfx/weapon_off.wav
  game/assets/sfx/weapon_on.wav
  game/database/resources/sfx/close-hand.json
  game/database/resources/sfx/condition-equip.json
  game/database/resources/sfx/condition-unequip.json
  game/database/resources/sfx/create-equipment.json
  game/database/resources/sfx/discard-card.json
  game/database/resources/sfx/dissolve.json
  game/database/resources/sfx/draw-card.json
  game/database/resources/sfx/focus-gain.json
  game/database/resources/sfx/open-hand.json
  game/database/resources/sfx/select-card.json
  game/database/resources/sfx/shuffle.json
  game/database/resources/sfx/wearable-equip.json
  game/database/resources/sfx/wearable-unequip.json
  game/database/resources/sfx/wieldable-equip.json
  game/database/resources/sfx/wieldable-unequip.json
  game/gamestates/animations/create_equipment_card.lua
  game/gamestates/animations/draw_card.lua
  game/gamestates/animations/play_widget_card.lua
  game/gamestates/animations/shuffle_buffers.lua
  game/view/dissolvecard.lua
  game/view/gameplay/actionhud/focusbar.lua
  game/view/gameplay/actionhud/hand/init.lua
  game/view/gameplay/actionhud/init.lua
Labels: music/sound

#1424 Tweak SFX
  game/assets/sfx/close_hand.wav
  game/assets/sfx/cond_off.wav
  game/assets/sfx/cond_on.wav
  game/assets/sfx/discard-temporary-card.wav
  game/assets/sfx/equip_off.wav
  game/assets/sfx/equip_on.wav
  game/assets/sfx/get_hp.wav
  game/assets/sfx/get_pack.wav
  game/assets/sfx/get_pp.wav
  game/assets/sfx/open-pack.wav
  game/assets/sfx/open_hand.wav
  game/assets/sfx/toggle_card.wav
  game/assets/sfx/weapon_off.wav
  game/assets/sfx/weapon_on.wav
  game/database/resources/sfx/get-hp.json
  game/database/resources/sfx/get-pack.json
  game/database/resources/sfx/get-pp.json
  game/database/resources/sfx/open-pack.json
  game/database/resources/sfx/toggle-card.json
  game/domain/actor.lua
  game/gamestates/consume_cards.lua
  game/gamestates/open_pack.lua
Labels: music/sound
