Repository uspgamedev/backdoor, pull requests merged in 2020-09, with the labels that each got.

#1521 Fix deploy script
  Makefile
Labels: bug, devops

#1519 Increase delay after consuming cards
  game/view/consumelist.lua
Labels: bug

#1517 Simplify attribute modifier on cards
  game/database/domains/card/arcane-burst.json
  game/database/domains/card/bloodthirst.json
  game/database/domains/card/bone-club-crush.json
  game/database/domains/card/bone-club.json
  game/database/domains/card/chained-energy.json
  game/database/domains/card/chained-surge.json
  game/database/domains/card/change-of-plans.json
  game/database/domains/card/disposable-defenses.json
  game/database/domains/card/eletric.json
  game/database/domains/card/energy-shield.json
  game/database/domains/card/entangle.json
  game/database/domains/card/fireball.json
  game/database/domains/card/firebolt.json
  game/database/domains/card/flash.json
  game/database/domains/card/flurry-of-blows.json
  game/database/domains/card/greater-jump.json
  game/database/domains/card/greater-rush.json
  game/database/domains/card/heal.json
  game/database/domains/card/healing_potion.json
  game/database/domains/card/hide-vest.json
  game/database/domains/card/hook-n-uppercut.json
  game/database/domains/card/illusion_of_darkness.json
  game/database/domains/card/jump.json
  game/database/domains/card/lead-pipe-strike.json
  game/database/domains/card/light-drops.json
  game/database/domains/card/old-laddle-strike.json
  game/database/domains/card/plasma-bomb.json
  game/database/domains/card/plated-shield.json
  game/database/domains/card/push.json
  game/database/domains/card/rage.json
  game/database/domains/card/reckless-smash.json
  game/database/domains/card/reinforce.json
  game/database/domains/card/roundhouse-kick.json
  game/database/domains/card/rush.json
  game/database/domains/card/signet-of-inspiration.json
  game/database/domains/card/sonic-boom.json
  game/database/domains/card/soul_robe.json
  game/database/domains/card/spark-rod-aoe.json
  game/database/domains/card/spark-rod-target.json
  game/database/domains/card/static-field.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/sticky_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/strike.json
  game/database/domains/card/stunning-blow.json
  game/database/domains/card/teleport.json
  game/database/domains/card/wrench.json
  game/database/schema/card.lua
  game/domain/ability.lua
  game/domain/body.lua
  game/domain/card.lua
  game/domain/definitions/attribute.lua
  game/domain/effects/place_widget.lua
  game/domain/effects/place_widget_on_area.lua
  game/domain/maneuver/play_card.lua
  game/domain/operators/effective_power.lua
  game/domain/transformers/props.lua
Labels: UX, content, feature, gameplay

#1523 Nerf slime and imp decks
  game/database/domains/actor/dumb-slime.json
  game/database/domains/actor/grinful-imp.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
Labels: content, gameplay

#1522 Add chest prop
  game/assets/texture/chest.png
  game/database/domains/appearance/prop-chest.json
  game/database/domains/body/chest.json
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
  game/database/domains/sector/sector_final.json
  game/database/resources/sprite/prop-chest.json
  game/database/resources/texture/prop-chest.json
Labels: content, gameplay

#1524 Different packs for different collections
  game/assets/texture/doggo_pack.png
  game/assets/texture/eye_pack.png
  game/assets/texture/imp_pack.png
  game/assets/texture/slime_pack.png
  game/assets/texture/stove_pack.png
  game/database/domains/collection/anything.json
  game/database/domains/collection/doggo.json
  game/database/domains/collection/eye.json
  game/database/domains/collection/imp.json
  game/database/domains/collection/slime.json
  game/database/domains/collection/stove.json
  game/database/resources/texture/pack-doggo.json
  game/database/resources/texture/pack-eye.json
  game/database/resources/texture/pack-imp.json
  game/database/resources/texture/pack-slime.json
  game/database/resources/texture/pack-stove.json
  game/database/schema/collection.lua
  game/database/settings/controls.json
  game/domain/definitions/colors.lua
  game/main.lua
  game/view/packlist.lua
Labels: juice

#1525 Recolor unplayable card to improve contrast
  game/domain/definitions/colors.lua
  game/view/helpers/card.lua
Labels: UX, bug

#1526 Reduce food/pack drops since crates exist
  game/database/domains/sector/sector01.json
  game/database/domains/sector/sector02.json
  game/database/domains/sector/sector03.json
Labels: content, gameplay

#1527 Only calculate highlight when hitscan changes
  game/view/sector.lua
Labels: graphics, refactoring

#1528 Only draw elements within camera frame
  game/common/camera.lua
  game/view/sector.lua
Labels: graphics, refactoring

#1529 Use getPlayerActor instead of getControlledActor
  game/gamestates/animations/place_widget_card.lua
  game/view/sector/bodyview.lua
Labels: bug

#1531 Do not try to place drops when there aren't any
  game/domain/builders/sector.lua
Labels: bug

#1530 Update FoV only when strictly necessary
  game/domain/actor.lua
  game/domain/sector.lua
Labels: refactoring

#1535 Destroy widgets when their owners die
  game/domain/body.lua
  game/domain/effects/place_widget.lua
  game/domain/effects/place_widget_on_area.lua
  game/domain/gameelement.lua
  game/domain/sector.lua
Labels: bug

#1536 Character Selection Screen
  game/gamestates/animations/absorb_damage.lua
  game/view/card.lua
  game/view/charabuild.lua
Labels: interface

#1544 Refactor armor mechanic
  game/database/domains/card/disposable-defenses.json
  game/database/domains/card/energy-shield.json
  game/database/domains/card/entangle.json
  game/database/domains/card/fix-turret.json
  game/database/domains/card/flash.json
  game/database/domains/card/heal.json
  game/database/domains/card/hide-vest.json
  game/database/domains/card/illusion_of_darkness.json
  game/database/domains/card/impact-vest.json
  game/database/domains/card/plated-shield.json
  game/database/domains/card/power-suit.json
  game/database/domains/card/push.json
  game/database/domains/card/reassemble.json
  game/database/domains/card/reinforce.json
  game/database/domains/card/reinforced-surface.json
  game/database/domains/card/soul_robe.json
  game/database/domains/card/static-field.json
  game/database/domains/card/stick_flame.json
  game/database/domains/card/stomp.json
  game/database/domains/card/stunning-blow.json
  game/database/domains/card/trained-strike.json
  game/database/schema/card.lua
  game/domain/body.lua
  game/domain/card.lua
  game/view/card.lua
Labels: UX, refactoring
